// ===================================================================
// Admission Prep Question Bank — সেট ২ (সম্প্রসারণ)
// -------------------------------------------------------------------
// `seed-admission-questions.ts` (৫৩টা প্রশ্ন) এর **সম্পূরক** — সেটা
// মুছে না ফেলে আরও ১৬৭টা প্রশ্ন যোগ করে। ফলে মোট ২২০টা হয়, যা
// `lib/admission.ts` এর কনফিগের পূর্ণ চাহিদা মেটায়:
//   • MEDICAL   ১০০ (Bio 30, Chem 25, Phy 15, Eng 15, GK 15)
//   • DU_A_UNIT  ৬০ (Phy/Chem/Math/Bio ১৫ করে)
//   • BUET       ৬০ (Math/Phy/Chem ২০ করে)
//
// ⚠️ গুরুত্বপূর্ণ: এই স্ক্রিপ্ট `deleteMany` করে **না** — কারণ মূল
// স্ক্রিপ্টটা idempotent হিসেবে নিজেই সব মুছে বসায়। সঠিক ক্রম:
//     pnpm db:seed-admission-questions      (৫৩টা — আগে)
//     pnpm db:seed-admission-questions-2    (১৬৭টা — পরে)
//
// পুনরায় চালালে ডুপ্লিকেট এড়াতে এখানে text-ভিত্তিক চেক আছে।
//
// রান: pnpm db:seed-admission-questions-2
// ===================================================================
import { PrismaClient, Difficulty, AdmissionExamType, AdmissionSubject } from "@prisma/client";

const prisma = new PrismaClient();

interface AdmissionQuestionSeed {
  examType: AdmissionExamType;
  subject: AdmissionSubject;
  text: string;
  options: string[];
  correctAnswer: string;
  explanation: string;
  difficulty: Difficulty;
}

const questions: AdmissionQuestionSeed[] = [

  // ==================== MEDICAL — BIOLOGY ====================
  {
    examType: "MEDICAL",
    subject: "BIOLOGY",
    text: "মানবদেহের বৃহত্তম গ্রন্থি কোনটি?",
    options: ["যকৃত", "অগ্ন্যাশয়", "থাইরয়েড", "প্লীহা"],
    correctAnswer: "যকৃত",
    explanation: "যকৃত (Liver) মানবদেহের বৃহত্তম গ্রন্থি ও বৃহত্তম অভ্যন্তরীণ অঙ্গ।",
    difficulty: "EASY",
  },
  {
    examType: "MEDICAL",
    subject: "BIOLOGY",
    text: "রাইবোজোমের প্রধান কাজ কী?",
    options: ["প্রোটিন সংশ্লেষণ", "শ্বসন", "সালোকসংশ্লেষণ", "বর্জ্য নিষ্কাশন"],
    correctAnswer: "প্রোটিন সংশ্লেষণ",
    explanation: "রাইবোজোম mRNA এর কোড অনুযায়ী অ্যামিনো অ্যাসিড জুড়ে প্রোটিন তৈরি করে।",
    difficulty: "EASY",
  },
  {
    examType: "MEDICAL",
    subject: "BIOLOGY",
    text: "মানবদেহে রক্তের pH এর স্বাভাবিক মান কত?",
    options: ["৬.৪ – ৬.৮", "৭.৩৫ – ৭.৪৫", "৮.০ – ৮.৫", "৫.৫ – ৬.০"],
    correctAnswer: "৭.৩৫ – ৭.৪৫",
    explanation: "রক্ত সামান্য ক্ষারীয়; বাফার সিস্টেম এই সংকীর্ণ পরিসর বজায় রাখে।",
    difficulty: "MEDIUM",
  },
  {
    examType: "MEDICAL",
    subject: "BIOLOGY",
    text: "কোন ভিটামিনের অভাবে রাতকানা রোগ হয়?",
    options: ["ভিটামিন A", "ভিটামিন C", "ভিটামিন D", "ভিটামিন K"],
    correctAnswer: "ভিটামিন A",
    explanation: "ভিটামিন A রেটিনার রোডপসিন তৈরিতে দরকার; অভাবে অন্ধকারে দেখা যায় না।",
    difficulty: "EASY",
  },
  {
    examType: "MEDICAL",
    subject: "BIOLOGY",
    text: "হৃৎপিণ্ডের কোন প্রকোষ্ঠ থেকে অ্যাওর্টা বের হয়?",
    options: ["বাম নিলয়", "ডান নিলয়", "বাম অলিন্দ", "ডান অলিন্দ"],
    correctAnswer: "বাম নিলয়",
    explanation: "বাম নিলয় সবচেয়ে পুরু প্রাচীরযুক্ত; এখান থেকে অ্যাওর্টা দিয়ে অক্সিজেনযুক্ত রক্ত সারা দেহে যায়।",
    difficulty: "MEDIUM",
  },
  {
    examType: "MEDICAL",
    subject: "BIOLOGY",
    text: "নেফ্রন কোন অঙ্গের গাঠনিক একক?",
    options: ["বৃক্ক", "ফুসফুস", "যকৃত", "প্লীহা"],
    correctAnswer: "বৃক্ক",
    explanation: "নেফ্রন বৃক্কের কার্যকরী ও গাঠনিক একক; প্রতিটি বৃক্কে প্রায় ১০ লক্ষ নেফ্রন থাকে।",
    difficulty: "EASY",
  },
  {
    examType: "MEDICAL",
    subject: "BIOLOGY",
    text: "ট্রান্সক্রিপশন প্রক্রিয়ায় কী তৈরি হয়?",
    options: ["mRNA", "প্রোটিন", "DNA", "লিপিড"],
    correctAnswer: "mRNA",
    explanation: "DNA টেমপ্লেট থেকে RNA পলিমারেজ এনজাইম mRNA সংশ্লেষ করে।",
    difficulty: "MEDIUM",
  },
  {
    examType: "MEDICAL",
    subject: "BIOLOGY",
    text: "মানুষের বৃহত্তম কোষ কোনটি?",
    options: ["ডিম্বাণু", "শুক্রাণু", "স্নায়ুকোষ", "লোহিত রক্তকণিকা"],
    correctAnswer: "ডিম্বাণু",
    explanation: "মানব ডিম্বাণুর ব্যাস প্রায় ১২০ মাইক্রোমিটার — খালি চোখে প্রায় দৃশ্যমান।",
    difficulty: "MEDIUM",
  },
  {
    examType: "MEDICAL",
    subject: "BIOLOGY",
    text: "কোন রক্তগ্রুপকে সর্বজনীন দাতা বলা হয়?",
    options: ["O নেগেটিভ", "AB পজিটিভ", "A পজিটিভ", "B নেগেটিভ"],
    correctAnswer: "O নেগেটিভ",
    explanation: "O নেগেটিভ রক্তে A, B অ্যান্টিজেন ও Rh ফ্যাক্টর নেই, তাই যে কাউকে দেওয়া যায়।",
    difficulty: "MEDIUM",
  },
  {
    examType: "MEDICAL",
    subject: "BIOLOGY",
    text: "ক্রেবস চক্র কোষের কোথায় ঘটে?",
    options: ["মাইটোকন্ড্রিয়ার ম্যাট্রিক্সে", "সাইটোপ্লাজমে", "নিউক্লিয়াসে", "রাইবোজোমে"],
    correctAnswer: "মাইটোকন্ড্রিয়ার ম্যাট্রিক্সে",
    explanation: "গ্লাইকোলাইসিস সাইটোপ্লাজমে হলেও ক্রেবস চক্র মাইটোকন্ড্রিয়ার ম্যাট্রিক্সে সম্পন্ন হয়।",
    difficulty: "HARD",
  },
  {
    examType: "MEDICAL",
    subject: "BIOLOGY",
    text: "কোন হরমোন রক্তে গ্লুকোজের মাত্রা বাড়ায়?",
    options: ["গ্লুকাগন", "ইনসুলিন", "থাইরক্সিন", "অক্সিটোসিন"],
    correctAnswer: "গ্লুকাগন",
    explanation: "অগ্ন্যাশয়ের আলফা কোষ থেকে নিঃসৃত গ্লুকাগন গ্লাইকোজেন ভেঙে গ্লুকোজ বাড়ায়।",
    difficulty: "MEDIUM",
  },
  {
    examType: "MEDICAL",
    subject: "BIOLOGY",
    text: "অ্যান্টিবডি কোন কোষ থেকে উৎপন্ন হয়?",
    options: ["প্লাজমা কোষ (B লিম্ফোসাইট)", "T লিম্ফোসাইট", "লোহিত রক্তকণিকা", "অণুচক্রিকা"],
    correctAnswer: "প্লাজমা কোষ (B লিম্ফোসাইট)",
    explanation: "B লিম্ফোসাইট সক্রিয় হয়ে প্লাজমা কোষে পরিণত হয় ও অ্যান্টিবডি ক্ষরণ করে।",
    difficulty: "MEDIUM",
  },
  {
    examType: "MEDICAL",
    subject: "BIOLOGY",
    text: "মানবদেহের দীর্ঘতম কোষ কোনটি?",
    options: ["স্নায়ুকোষ", "পেশিকোষ", "অস্থিকোষ", "ত্বককোষ"],
    correctAnswer: "স্নায়ুকোষ",
    explanation: "কিছু নিউরনের অ্যাক্সন এক মিটারের বেশি লম্বা হতে পারে।",
    difficulty: "EASY",
  },
  {
    examType: "MEDICAL",
    subject: "BIOLOGY",
    text: "লোহিত রক্তকণিকার গড় আয়ুষ্কাল কত দিন?",
    options: ["১২০ দিন", "৩০ দিন", "৭ দিন", "৩৬৫ দিন"],
    correctAnswer: "১২০ দিন",
    explanation: "পরিণত RBC এ নিউক্লিয়াস না থাকায় প্রায় ১২০ দিন পর প্লীহায় ধ্বংস হয়।",
    difficulty: "MEDIUM",
  },
  {
    examType: "MEDICAL",
    subject: "BIOLOGY",
    text: "কোন এনজাইম স্টার্চকে ভাঙে?",
    options: ["অ্যামাইলেজ", "পেপসিন", "লাইপেজ", "ট্রিপসিন"],
    correctAnswer: "অ্যামাইলেজ",
    explanation: "লালা ও অগ্ন্যাশয়ের অ্যামাইলেজ স্টার্চকে মল্টোজে পরিণত করে।",
    difficulty: "EASY",
  },
  {
    examType: "MEDICAL",
    subject: "BIOLOGY",
    text: "মানুষের মেরুদণ্ডে কতটি কশেরুকা থাকে?",
    options: ["৩৩টি", "২৪টি", "১২টি", "৪৫টি"],
    correctAnswer: "৩৩টি",
    explanation: "শিশুর ৩৩টি; প্রাপ্তবয়স্কে স্যাক্রাম ও কক্সিক্স জোড়া লেগে ২৬টি হাড় গণনা করা হয়।",
    difficulty: "HARD",
  },
  {
    examType: "MEDICAL",
    subject: "BIOLOGY",
    text: "সালোকসংশ্লেষণে অক্সিজেন কোথা থেকে আসে?",
    options: ["পানি", "কার্বন ডাই-অক্সাইড", "গ্লুকোজ", "ক্লোরোফিল"],
    correctAnswer: "পানি",
    explanation: "আলোক পর্যায়ে পানির ফটোলাইসিসে O₂ নির্গত হয় — আইসোটোপ পরীক্ষায় প্রমাণিত।",
    difficulty: "HARD",
  },
  {
    examType: "MEDICAL",
    subject: "BIOLOGY",
    text: "ভাইরাসের জেনেটিক বস্তু কী হতে পারে?",
    options: ["DNA অথবা RNA", "শুধু DNA", "শুধু RNA", "প্রোটিন"],
    correctAnswer: "DNA অথবা RNA",
    explanation: "ভাইরাসভেদে জেনেটিক বস্তু DNA (হেপাটাইটিস B) বা RNA (HIV, ইনফ্লুয়েঞ্জা) হয়।",
    difficulty: "MEDIUM",
  },
  {
    examType: "MEDICAL",
    subject: "BIOLOGY",
    text: "কোন অঙ্গ পিত্তরস সঞ্চয় করে?",
    options: ["পিত্তথলি", "যকৃত", "অগ্ন্যাশয়", "পাকস্থলী"],
    correctAnswer: "পিত্তথলি",
    explanation: "যকৃত পিত্তরস তৈরি করে, পিত্তথলি তা ঘনীভূত করে সঞ্চয় রাখে।",
    difficulty: "EASY",
  },
  {
    examType: "MEDICAL",
    subject: "BIOLOGY",
    text: "মাইটোসিস কোষ বিভাজনে কয়টি অপত্য কোষ তৈরি হয়?",
    options: ["২টি", "৪টি", "১টি", "৮টি"],
    correctAnswer: "২টি",
    explanation: "মাইটোসিসে একটি মাতৃকোষ থেকে জিনগতভাবে অভিন্ন ২টি অপত্য কোষ তৈরি হয়।",
    difficulty: "EASY",
  },
  {
    examType: "MEDICAL",
    subject: "BIOLOGY",
    text: "কোন ভিটামিন রক্ত জমাট বাঁধতে সাহায্য করে?",
    options: ["ভিটামিন K", "ভিটামিন C", "ভিটামিন B12", "ভিটামিন E"],
    correctAnswer: "ভিটামিন K",
    explanation: "ভিটামিন K যকৃতে প্রোথ্রম্বিন সংশ্লেষণে অপরিহার্য।",
    difficulty: "MEDIUM",
  },
  {
    examType: "MEDICAL",
    subject: "BIOLOGY",
    text: "মানবদেহে সবচেয়ে বড় ধমনী কোনটি?",
    options: ["অ্যাওর্টা", "পালমোনারি ধমনী", "ক্যারোটিড ধমনী", "রেনাল ধমনী"],
    correctAnswer: "অ্যাওর্টা",
    explanation: "অ্যাওর্টা বাম নিলয় থেকে উৎপন্ন হয়ে সারা দেহে অক্সিজেনযুক্ত রক্ত সরবরাহ করে।",
    difficulty: "EASY",
  },

  // ==================== MEDICAL — CHEMISTRY ====================
  {
    examType: "MEDICAL",
    subject: "CHEMISTRY",
    text: "অ্যাভোগাড্রো সংখ্যার মান কত?",
    options: ["6.022 × 10²³", "3.14 × 10⁸", "9.8 × 10⁻³", "1.6 × 10⁻¹⁹"],
    correctAnswer: "6.022 × 10²³",
    explanation: "১ মোল পদার্থে 6.022 × 10²³ টি কণা থাকে।",
    difficulty: "EASY",
  },
  {
    examType: "MEDICAL",
    subject: "CHEMISTRY",
    text: "পর্যায় সারণিতে সবচেয়ে তড়িৎ-ঋণাত্মক মৌল কোনটি?",
    options: ["ফ্লোরিন", "অক্সিজেন", "ক্লোরিন", "নাইট্রোজেন"],
    correctAnswer: "ফ্লোরিন",
    explanation: "পলিং স্কেলে ফ্লোরিনের তড়িৎ-ঋণাত্মকতা ৩.৯৮ — সর্বোচ্চ।",
    difficulty: "MEDIUM",
  },
  {
    examType: "MEDICAL",
    subject: "CHEMISTRY",
    text: "একটি ইলেকট্রনের আধান কত?",
    options: ["−1.6 × 10⁻¹⁹ C", "+1.6 × 10⁻¹⁹ C", "−9.1 × 10⁻³¹ C", "0"],
    correctAnswer: "−1.6 × 10⁻¹⁹ C",
    explanation: "ইলেকট্রনের আধান ঋণাত্মক, মান 1.6 × 10⁻¹⁹ কুলম্ব।",
    difficulty: "MEDIUM",
  },
  {
    examType: "MEDICAL",
    subject: "CHEMISTRY",
    text: "NaOH এর জলীয় দ্রবণ কেমন?",
    options: ["ক্ষারীয়", "আম্লিক", "নিরপেক্ষ", "উভধর্মী"],
    correctAnswer: "ক্ষারীয়",
    explanation: "NaOH একটি শক্তিশালী ক্ষার; জলীয় দ্রবণে OH⁻ আয়ন দেয়, pH > ৭।",
    difficulty: "EASY",
  },
  {
    examType: "MEDICAL",
    subject: "CHEMISTRY",
    text: "কোনটি নোবেল গ্যাস?",
    options: ["আর্গন", "অক্সিজেন", "নাইট্রোজেন", "হাইড্রোজেন"],
    correctAnswer: "আর্গন",
    explanation: "আর্গন গ্রুপ ১৮ এর নিষ্ক্রিয় গ্যাস; বহিঃস্তর সম্পূর্ণ পূর্ণ।",
    difficulty: "EASY",
  },
  {
    examType: "MEDICAL",
    subject: "CHEMISTRY",
    text: "মিথেনের (CH₄) সংকরায়ন কী?",
    options: ["sp³", "sp²", "sp", "dsp²"],
    correctAnswer: "sp³",
    explanation: "কার্বনের ৪টি সিগমা বন্ধন sp³ সংকরায়নে চতুস্তলকীয় আকার দেয় (১০৯.৫°)।",
    difficulty: "HARD",
  },
  {
    examType: "MEDICAL",
    subject: "CHEMISTRY",
    text: "অক্সিডেশন বলতে কী বোঝায়?",
    options: ["ইলেকট্রন ত্যাগ", "ইলেকট্রন গ্রহণ", "প্রোটন ত্যাগ", "নিউট্রন গ্রহণ"],
    correctAnswer: "ইলেকট্রন ত্যাগ",
    explanation: "জারণে পদার্থ ইলেকট্রন হারায় ও জারণ সংখ্যা বাড়ে।",
    difficulty: "MEDIUM",
  },
  {
    examType: "MEDICAL",
    subject: "CHEMISTRY",
    text: "একটি পরমাণুর ভর সংখ্যা কী নির্দেশ করে?",
    options: ["প্রোটন ও নিউট্রনের যোগফল", "শুধু প্রোটন সংখ্যা", "শুধু ইলেকট্রন সংখ্যা", "প্রোটন ও ইলেকট্রনের যোগফল"],
    correctAnswer: "প্রোটন ও নিউট্রনের যোগফল",
    explanation: "ভর সংখ্যা (A) = প্রোটন (Z) + নিউট্রন (N)।",
    difficulty: "EASY",
  },
  {
    examType: "MEDICAL",
    subject: "CHEMISTRY",
    text: "গ্লুকোজের আণবিক সংকেত কী?",
    options: ["C₆H₁₂O₆", "C₂H₅OH", "CH₃COOH", "C₆H₆"],
    correctAnswer: "C₆H₁₂O₆",
    explanation: "গ্লুকোজ একটি মনোস্যাকারাইড; আণবিক ভর ১৮০ g/mol।",
    difficulty: "EASY",
  },
  {
    examType: "MEDICAL",
    subject: "CHEMISTRY",
    text: "কোন গ্যাসটি গ্রিনহাউস প্রভাবের জন্য প্রধানত দায়ী?",
    options: ["কার্বন ডাই-অক্সাইড", "অক্সিজেন", "নাইট্রোজেন", "হিলিয়াম"],
    correctAnswer: "কার্বন ডাই-অক্সাইড",
    explanation: "CO₂ ইনফ্রারেড বিকিরণ শোষণ করে বায়ুমণ্ডলে তাপ আটকে রাখে।",
    difficulty: "EASY",
  },
  {
    examType: "MEDICAL",
    subject: "CHEMISTRY",
    text: "আয়নিক বন্ধন কীভাবে গঠিত হয়?",
    options: ["ইলেকট্রন স্থানান্তরে", "ইলেকট্রন শেয়ারে", "প্রোটন বিনিময়ে", "নিউট্রন স্থানান্তরে"],
    correctAnswer: "ইলেকট্রন স্থানান্তরে",
    explanation: "ধাতু ইলেকট্রন দেয়, অধাতু নেয় — বিপরীত আধানের আকর্ষণে বন্ধন হয়।",
    difficulty: "MEDIUM",
  },
  {
    examType: "MEDICAL",
    subject: "CHEMISTRY",
    text: "১ মোল যেকোনো গ্যাসের STP তে আয়তন কত?",
    options: ["22.4 লিটার", "11.2 লিটার", "44.8 লিটার", "1 লিটার"],
    correctAnswer: "22.4 লিটার",
    explanation: "STP (০°C, ১ atm) এ ১ মোল আদর্শ গ্যাসের মোলার আয়তন ২২.৪ লিটার।",
    difficulty: "MEDIUM",
  },
  {
    examType: "MEDICAL",
    subject: "CHEMISTRY",
    text: "কোনটি শক্তিশালী অ্যাসিড?",
    options: ["HCl", "CH₃COOH", "H₂CO₃", "H₃BO₃"],
    correctAnswer: "HCl",
    explanation: "HCl জলীয় দ্রবণে সম্পূর্ণরূপে বিয়োজিত হয়, বাকিগুলো দুর্বল অ্যাসিড।",
    difficulty: "EASY",
  },
  {
    examType: "MEDICAL",
    subject: "CHEMISTRY",
    text: "প্রভাবক (Catalyst) বিক্রিয়ায় কী করে?",
    options: ["সক্রিয়করণ শক্তি কমায়", "সাম্যাবস্থা সরায়", "বিক্রিয়কের পরিমাণ বাড়ায়", "তাপ উৎপন্ন করে"],
    correctAnswer: "সক্রিয়করণ শক্তি কমায়",
    explanation: "প্রভাবক বিকল্প পথে বিক্রিয়া ঘটিয়ে সক্রিয়করণ শক্তি কমায়, নিজে অপরিবর্তিত থাকে।",
    difficulty: "MEDIUM",
  },
  {
    examType: "MEDICAL",
    subject: "CHEMISTRY",
    text: "পানির স্ফুটনাঙ্ক ১০০°C হওয়ার কারণ কী?",
    options: ["হাইড্রোজেন বন্ধন", "আয়নিক বন্ধন", "ধাতব বন্ধন", "সমযোজী বন্ধন"],
    correctAnswer: "হাইড্রোজেন বন্ধন",
    explanation: "পানির অণুগুলোর মধ্যে শক্তিশালী হাইড্রোজেন বন্ধন ভাঙতে বেশি তাপ লাগে।",
    difficulty: "MEDIUM",
  },
  {
    examType: "MEDICAL",
    subject: "CHEMISTRY",
    text: "অ্যালকেনের সাধারণ সংকেত কী?",
    options: ["CₙH₂ₙ₊₂", "CₙH₂ₙ", "CₙH₂ₙ₋₂", "CₙH₂ₙO"],
    correctAnswer: "CₙH₂ₙ₊₂",
    explanation: "অ্যালকেন সম্পৃক্ত হাইড্রোকার্বন; সব বন্ধন একক।",
    difficulty: "MEDIUM",
  },
  {
    examType: "MEDICAL",
    subject: "CHEMISTRY",
    text: "তেজস্ক্রিয়তায় আলফা কণা কী?",
    options: ["হিলিয়াম নিউক্লিয়াস", "ইলেকট্রন", "ফোটন", "নিউট্রন"],
    correctAnswer: "হিলিয়াম নিউক্লিয়াস",
    explanation: "আলফা কণা = ২টি প্রোটন + ২টি নিউট্রন, অর্থাৎ He²⁺ নিউক্লিয়াস।",
    difficulty: "HARD",
  },
  {
    examType: "MEDICAL",
    subject: "CHEMISTRY",
    text: "কোনটি জারক পদার্থ?",
    options: ["KMnO₄", "H₂", "Na", "Zn"],
    correctAnswer: "KMnO₄",
    explanation: "পটাশিয়াম পারম্যাঙ্গানেট শক্তিশালী জারক; নিজে বিজারিত হয়ে অন্যকে জারিত করে।",
    difficulty: "MEDIUM",
  },

  // ==================== MEDICAL — PHYSICS ====================
  {
    examType: "MEDICAL",
    subject: "PHYSICS",
    text: "কাজের SI একক কী?",
    options: ["জুল", "নিউটন", "ওয়াট", "প্যাসকেল"],
    correctAnswer: "জুল",
    explanation: "কাজ = বল × সরণ; ১ জুল = ১ নিউটন × ১ মিটার।",
    difficulty: "EASY",
  },
  {
    examType: "MEDICAL",
    subject: "PHYSICS",
    text: "অভিকর্ষজ ত্বরণের আদর্শ মান কত?",
    options: ["9.8 m/s²", "10.8 m/s²", "8.9 m/s²", "6.7 m/s²"],
    correctAnswer: "9.8 m/s²",
    explanation: "পৃথিবীপৃষ্ঠে g এর আদর্শ মান ৯.৮ m/s² (প্রায় ৯.৮১)।",
    difficulty: "EASY",
  },
  {
    examType: "MEDICAL",
    subject: "PHYSICS",
    text: "ক্ষমতার SI একক কী?",
    options: ["ওয়াট", "জুল", "নিউটন", "হার্জ"],
    correctAnswer: "ওয়াট",
    explanation: "ক্ষমতা = কাজ/সময়; ১ ওয়াট = ১ জুল/সেকেন্ড।",
    difficulty: "EASY",
  },
  {
    examType: "MEDICAL",
    subject: "PHYSICS",
    text: "আলোর প্রতিসরণে কোন রাশি অপরিবর্তিত থাকে?",
    options: ["কম্পাঙ্ক", "তরঙ্গদৈর্ঘ্য", "বেগ", "বিস্তার"],
    correctAnswer: "কম্পাঙ্ক",
    explanation: "মাধ্যম বদলালে বেগ ও তরঙ্গদৈর্ঘ্য বদলায়, কিন্তু কম্পাঙ্ক উৎসের উপর নির্ভরশীল বলে অপরিবর্তিত থাকে।",
    difficulty: "HARD",
  },
  {
    examType: "MEDICAL",
    subject: "PHYSICS",
    text: "ওহমের সূত্র অনুযায়ী V = ?",
    options: ["IR", "I/R", "R/I", "I²R"],
    correctAnswer: "IR",
    explanation: "ওহমের সূত্র: বিভব পার্থক্য = প্রবাহ × রোধ।",
    difficulty: "EASY",
  },
  {
    examType: "MEDICAL",
    subject: "PHYSICS",
    text: "তাপগতিবিদ্যার প্রথম সূত্র কীসের সংরক্ষণ প্রকাশ করে?",
    options: ["শক্তি", "ভরবেগ", "আধান", "ভর"],
    correctAnswer: "শক্তি",
    explanation: "ΔU = Q − W — এটি শক্তির নিত্যতা সূত্রের রূপ।",
    difficulty: "MEDIUM",
  },
  {
    examType: "MEDICAL",
    subject: "PHYSICS",
    text: "লেন্সের ক্ষমতার একক কী?",
    options: ["ডায়প্টার", "মিটার", "লাক্স", "ক্যান্ডেলা"],
    correctAnswer: "ডায়প্টার",
    explanation: "লেন্সের ক্ষমতা P = 1/f (f মিটারে); একক ডায়প্টার (D)।",
    difficulty: "MEDIUM",
  },
  {
    examType: "MEDICAL",
    subject: "PHYSICS",
    text: "শব্দ কোন ধরনের তরঙ্গ?",
    options: ["অনুদৈর্ঘ্য", "অনুপ্রস্থ", "তড়িৎচুম্বকীয়", "স্থির"],
    correctAnswer: "অনুদৈর্ঘ্য",
    explanation: "শব্দ তরঙ্গে কণার কম্পন তরঙ্গ চলার দিকেই হয়, তাই এটি অনুদৈর্ঘ্য।",
    difficulty: "MEDIUM",
  },
  {
    examType: "MEDICAL",
    subject: "PHYSICS",
    text: "রোধের SI একক কী?",
    options: ["ওহম", "অ্যাম্পিয়ার", "ভোল্ট", "ওয়াট"],
    correctAnswer: "ওহম",
    explanation: "রোধের একক ওহম (Ω), ওহমের সূত্র থেকে R = V/I।",
    difficulty: "EASY",
  },
  {
    examType: "MEDICAL",
    subject: "PHYSICS",
    text: "X-রশ্মি কোন ধরনের তরঙ্গ?",
    options: ["তড়িৎচুম্বকীয়", "শব্দ", "যান্ত্রিক", "পদার্থ"],
    correctAnswer: "তড়িৎচুম্বকীয়",
    explanation: "X-রশ্মি উচ্চ কম্পাঙ্কের তড়িৎচুম্বকীয় তরঙ্গ; শূন্যস্থানে চলতে পারে।",
    difficulty: "MEDIUM",
  },

  // ==================== MEDICAL — ENGLISH ====================
  {
    examType: "MEDICAL",
    subject: "ENGLISH",
    text: "Choose the correct spelling:",
    options: ["Accommodation", "Acommodation", "Accomodation", "Acomodation"],
    correctAnswer: "Accommodation",
    explanation: "'Accommodation' has double 'c' and double 'm'.",
    difficulty: "MEDIUM",
  },
  {
    examType: "MEDICAL",
    subject: "ENGLISH",
    text: "Choose the synonym of 'Abundant':",
    options: ["Plentiful", "Scarce", "Meagre", "Sparse"],
    correctAnswer: "Plentiful",
    explanation: "'Abundant' means existing in large quantities — plentiful.",
    difficulty: "EASY",
  },
  {
    examType: "MEDICAL",
    subject: "ENGLISH",
    text: "What is the antonym of 'Optimistic'?",
    options: ["Pessimistic", "Hopeful", "Cheerful", "Positive"],
    correctAnswer: "Pessimistic",
    explanation: "'Pessimistic' means expecting the worst — the opposite of optimistic.",
    difficulty: "EASY",
  },
  {
    examType: "MEDICAL",
    subject: "ENGLISH",
    text: "Fill in the blank: She has been living here ___ 2015.",
    options: ["since", "for", "from", "by"],
    correctAnswer: "since",
    explanation: "'Since' is used with a point of time; 'for' with a period.",
    difficulty: "MEDIUM",
  },
  {
    examType: "MEDICAL",
    subject: "ENGLISH",
    text: "Identify the correct passive voice: 'They build houses.'",
    options: ["Houses are built by them.", "Houses were built by them.", "Houses are being built.", "Houses have built."],
    correctAnswer: "Houses are built by them.",
    explanation: "Simple present active → 'am/is/are + past participle' in passive.",
    difficulty: "MEDIUM",
  },
  {
    examType: "MEDICAL",
    subject: "ENGLISH",
    text: "The word 'Ephemeral' means:",
    options: ["Short-lived", "Everlasting", "Enormous", "Ancient"],
    correctAnswer: "Short-lived",
    explanation: "'Ephemeral' describes something lasting for a very short time.",
    difficulty: "HARD",
  },
  {
    examType: "MEDICAL",
    subject: "ENGLISH",
    text: "Choose the correctly punctuated sentence:",
    options: ["He asked, “Are you coming?”", "He asked “are you coming?”", "He asked, “are you coming”.", "He asked; “Are you coming?”"],
    correctAnswer: "He asked, “Are you coming?”",
    explanation: "A comma precedes direct speech, which starts with a capital letter and keeps the question mark inside.",
    difficulty: "MEDIUM",
  },
  {
    examType: "MEDICAL",
    subject: "ENGLISH",
    text: "What is the noun form of 'Decide'?",
    options: ["Decision", "Deciding", "Decisive", "Decidedly"],
    correctAnswer: "Decision",
    explanation: "'Decision' is the noun; 'decisive' is the adjective and 'decidedly' the adverb.",
    difficulty: "EASY",
  },
  {
    examType: "MEDICAL",
    subject: "ENGLISH",
    text: "Fill in the blank: If I ___ rich, I would travel the world.",
    options: ["were", "am", "was", "will be"],
    correctAnswer: "were",
    explanation: "In the second conditional (unreal present), 'were' is used for all subjects.",
    difficulty: "HARD",
  },
  {
    examType: "MEDICAL",
    subject: "ENGLISH",
    text: "Choose the correct preposition: He is proud ___ his son.",
    options: ["of", "at", "for", "with"],
    correctAnswer: "of",
    explanation: "The fixed collocation is 'proud of'.",
    difficulty: "EASY",
  },
  {
    examType: "MEDICAL",
    subject: "ENGLISH",
    text: "The idiom 'to burn the midnight oil' means:",
    options: ["To study late at night", "To waste money", "To start a fire", "To sleep early"],
    correctAnswer: "To study late at night",
    explanation: "It refers to working or studying until late at night.",
    difficulty: "MEDIUM",
  },

  // ==================== MEDICAL — GENERAL_KNOWLEDGE ====================
  {
    examType: "MEDICAL",
    subject: "GENERAL_KNOWLEDGE",
    text: "বাংলাদেশের সংবিধান কার্যকর হয় কোন তারিখে?",
    options: ["১৬ ডিসেম্বর ১৯৭২", "২৬ মার্চ ১৯৭১", "১৪ ডিসেম্বর ১৯৭২", "২১ ফেব্রুয়ারি ১৯৭২"],
    correctAnswer: "১৬ ডিসেম্বর ১৯৭২",
    explanation: "গণপরিষদে গৃহীত সংবিধান ১৯৭২ সালের ১৬ ডিসেম্বর কার্যকর হয়।",
    difficulty: "MEDIUM",
  },
  {
    examType: "MEDICAL",
    subject: "GENERAL_KNOWLEDGE",
    text: "বাংলাদেশের জাতীয় ফুল কোনটি?",
    options: ["শাপলা", "গোলাপ", "জবা", "পদ্ম"],
    correctAnswer: "শাপলা",
    explanation: "সাদা শাপলা (Nymphaea nouchali) বাংলাদেশের জাতীয় ফুল।",
    difficulty: "EASY",
  },
  {
    examType: "MEDICAL",
    subject: "GENERAL_KNOWLEDGE",
    text: "WHO এর সদর দপ্তর কোথায়?",
    options: ["জেনেভা", "নিউইয়র্ক", "প্যারিস", "ভিয়েনা"],
    correctAnswer: "জেনেভা",
    explanation: "বিশ্ব স্বাস্থ্য সংস্থার সদর দপ্তর সুইজারল্যান্ডের জেনেভায়।",
    difficulty: "EASY",
  },
  {
    examType: "MEDICAL",
    subject: "GENERAL_KNOWLEDGE",
    text: "'অমর একুশে' কোন ঘটনার স্মারক?",
    options: ["ভাষা আন্দোলন", "মুক্তিযুদ্ধ", "গণঅভ্যুত্থান", "স্বাধীনতা ঘোষণা"],
    correctAnswer: "ভাষা আন্দোলন",
    explanation: "১৯৫২ সালের ২১ ফেব্রুয়ারি ভাষা শহীদদের আত্মত্যাগের স্মরণে।",
    difficulty: "EASY",
  },
  {
    examType: "MEDICAL",
    subject: "GENERAL_KNOWLEDGE",
    text: "বাংলাদেশের বৃহত্তম নদী কোনটি?",
    options: ["মেঘনা", "পদ্মা", "যমুনা", "কর্ণফুলী"],
    correctAnswer: "মেঘনা",
    explanation: "প্রশস্ততার দিক থেকে মেঘনা বাংলাদেশের বৃহত্তম নদী।",
    difficulty: "MEDIUM",
  },
  {
    examType: "MEDICAL",
    subject: "GENERAL_KNOWLEDGE",
    text: "জাতিসংঘ প্রতিষ্ঠিত হয় কোন সালে?",
    options: ["১৯৪৫", "১৯১৯", "১৯৫০", "১৯৬০"],
    correctAnswer: "১৯৪৫",
    explanation: "দ্বিতীয় বিশ্বযুদ্ধের পর ১৯৪৫ সালের ২৪ অক্টোবর জাতিসংঘ প্রতিষ্ঠিত হয়।",
    difficulty: "EASY",
  },
  {
    examType: "MEDICAL",
    subject: "GENERAL_KNOWLEDGE",
    text: "সুন্দরবন কোন কারণে বিখ্যাত?",
    options: ["রয়েল বেঙ্গল টাইগার", "হাতি", "গন্ডার", "সিংহ"],
    correctAnswer: "রয়েল বেঙ্গল টাইগার",
    explanation: "সুন্দরবন বিশ্বের বৃহত্তম ম্যানগ্রোভ বন ও রয়েল বেঙ্গল টাইগারের আবাসস্থল।",
    difficulty: "EASY",
  },
  {
    examType: "MEDICAL",
    subject: "GENERAL_KNOWLEDGE",
    text: "নোবেল পুরস্কার কোন দেশ থেকে দেওয়া হয়?",
    options: ["সুইডেন", "নরওয়ে", "ডেনমার্ক", "ফিনল্যান্ড"],
    correctAnswer: "সুইডেন",
    explanation: "শান্তি পুরস্কার নরওয়েতে দেওয়া হলেও বাকি সব সুইডেন থেকে দেওয়া হয়।",
    difficulty: "MEDIUM",
  },
  {
    examType: "MEDICAL",
    subject: "GENERAL_KNOWLEDGE",
    text: "বাংলাদেশের মুদ্রার নাম কী?",
    options: ["টাকা", "রুপি", "ডলার", "রিয়াল"],
    correctAnswer: "টাকা",
    explanation: "বাংলাদেশের সরকারি মুদ্রা টাকা (BDT)।",
    difficulty: "EASY",
  },
  {
    examType: "MEDICAL",
    subject: "GENERAL_KNOWLEDGE",
    text: "'৭ই মার্চের ভাষণ' কোথায় দেওয়া হয়েছিল?",
    options: ["রেসকোর্স ময়দান", "পল্টন ময়দান", "শহীদ মিনার", "কার্জন হল"],
    correctAnswer: "রেসকোর্স ময়দান",
    explanation: "১৯৭১ সালের ৭ মার্চ ঢাকার রেসকোর্স ময়দানে (বর্তমান সোহরাওয়ার্দী উদ্যান) ভাষণটি দেওয়া হয়।",
    difficulty: "MEDIUM",
  },
  {
    examType: "MEDICAL",
    subject: "GENERAL_KNOWLEDGE",
    text: "ইউনেস্কো ২১ ফেব্রুয়ারিকে আন্তর্জাতিক মাতৃভাষা দিবস ঘোষণা করে কোন সালে?",
    options: ["১৯৯৯", "১৯৫২", "২০০০", "১৯৭১"],
    correctAnswer: "১৯৯৯",
    explanation: "১৯৯৯ সালের ১৭ নভেম্বর ইউনেস্কো এই ঘোষণা দেয়, ২০০০ সাল থেকে পালিত হচ্ছে।",
    difficulty: "HARD",
  },

  // ==================== DU_A_UNIT — PHYSICS ====================
  {
    examType: "DU_A_UNIT",
    subject: "PHYSICS",
    text: "একটি বস্তু 20 m/s বেগে উপরে ছুড়লে সর্বোচ্চ কত উচ্চতায় উঠবে? (g=10)",
    options: ["20 m", "40 m", "10 m", "5 m"],
    correctAnswer: "20 m",
    explanation: "h = u²/2g = 400/20 = 20 মিটার।",
    difficulty: "MEDIUM",
  },
  {
    examType: "DU_A_UNIT",
    subject: "PHYSICS",
    text: "আপেক্ষিক তত্ত্ব অনুযায়ী কোন রাশি ধ্রুবক?",
    options: ["শূন্যে আলোর বেগ", "সময়", "দৈর্ঘ্য", "ভর"],
    correctAnswer: "শূন্যে আলোর বেগ",
    explanation: "আইনস্টাইনের বিশেষ আপেক্ষিকতায় c সব জড় প্রসঙ্গ কাঠামোয় ধ্রুবক।",
    difficulty: "HARD",
  },
  {
    examType: "DU_A_UNIT",
    subject: "PHYSICS",
    text: "কার্যাপেক্ষক (Work function) কোন ঘটনার সাথে সম্পর্কিত?",
    options: ["আলোক-তড়িৎ ক্রিয়া", "তাপ পরিবহন", "প্রতিসরণ", "ব্যতিচার"],
    correctAnswer: "আলোক-তড়িৎ ক্রিয়া",
    explanation: "ধাতু থেকে ইলেকট্রন বের করতে যে ন্যূনতম শক্তি লাগে তাই কার্যাপেক্ষক।",
    difficulty: "HARD",
  },
  {
    examType: "DU_A_UNIT",
    subject: "PHYSICS",
    text: "সমান্তরাল সংযোগে তিনটি 3Ω রোধের তুল্য রোধ কত?",
    options: ["1 Ω", "9 Ω", "3 Ω", "6 Ω"],
    correctAnswer: "1 Ω",
    explanation: "1/R = 1/3+1/3+1/3 = 1, তাই R = 1 Ω।",
    difficulty: "MEDIUM",
  },
  {
    examType: "DU_A_UNIT",
    subject: "PHYSICS",
    text: "তরঙ্গের বেগ, কম্পাঙ্ক ও তরঙ্গদৈর্ঘ্যের সম্পর্ক কী?",
    options: ["v = fλ", "v = f/λ", "v = λ/f", "v = f²λ"],
    correctAnswer: "v = fλ",
    explanation: "তরঙ্গের বেগ = কম্পাঙ্ক × তরঙ্গদৈর্ঘ্য।",
    difficulty: "EASY",
  },
  {
    examType: "DU_A_UNIT",
    subject: "PHYSICS",
    text: "নিউক্লিয়ার ফিশনে কী ঘটে?",
    options: ["ভারী নিউক্লিয়াস ভেঙে যায়", "হালকা নিউক্লিয়াস জোড়া লাগে", "ইলেকট্রন নির্গত হয়", "প্রোটন শোষিত হয়"],
    correctAnswer: "ভারী নিউক্লিয়াস ভেঙে যায়",
    explanation: "ফিশনে ইউরেনিয়ামের মতো ভারী নিউক্লিয়াস ভেঙে বিপুল শক্তি নির্গত হয়।",
    difficulty: "MEDIUM",
  },
  {
    examType: "DU_A_UNIT",
    subject: "PHYSICS",
    text: "চুম্বক ক্ষেত্রের SI একক কী?",
    options: ["টেসলা", "ওয়েবার", "হেনরি", "গাউস"],
    correctAnswer: "টেসলা",
    explanation: "চৌম্বক ফ্লাক্স ঘনত্বের SI একক টেসলা (T)।",
    difficulty: "MEDIUM",
  },
  {
    examType: "DU_A_UNIT",
    subject: "PHYSICS",
    text: "স্থির তরঙ্গে নিস্পন্দ বিন্দু কোনটি?",
    options: ["Node", "Antinode", "Crest", "Trough"],
    correctAnswer: "Node",
    explanation: "যেখানে বিস্তার শূন্য সেটাই node বা নিস্পন্দ বিন্দু।",
    difficulty: "MEDIUM",
  },
  {
    examType: "DU_A_UNIT",
    subject: "PHYSICS",
    text: "একটি সরল দোলকের পর্যায়কাল কীসের উপর নির্ভর করে না?",
    options: ["ববের ভরের", "দৈর্ঘ্যের", "অভিকর্ষজ ত্বরণের", "কোনোটিই নয়"],
    correctAnswer: "ববের ভরের",
    explanation: "T = 2π√(l/g) — ভর এই সমীকরণে নেই।",
    difficulty: "MEDIUM",
  },
  {
    examType: "DU_A_UNIT",
    subject: "PHYSICS",
    text: "লেন্জের সূত্র কোন সংরক্ষণ নীতি মেনে চলে?",
    options: ["শক্তির সংরক্ষণ", "ভরবেগের সংরক্ষণ", "আধানের সংরক্ষণ", "ভরের সংরক্ষণ"],
    correctAnswer: "শক্তির সংরক্ষণ",
    explanation: "আবিষ্ট প্রবাহের দিক এমন যে তা পরিবর্তনের বিরোধিতা করে — শক্তি সংরক্ষণের ফল।",
    difficulty: "HARD",
  },
  {
    examType: "DU_A_UNIT",
    subject: "PHYSICS",
    text: "আদর্শ গ্যাস সমীকরণ কোনটি?",
    options: ["PV = nRT", "PV = mRT", "P/V = nRT", "PV² = nRT"],
    correctAnswer: "PV = nRT",
    explanation: "আদর্শ গ্যাসের অবস্থা সমীকরণ PV = nRT।",
    difficulty: "EASY",
  },

  // ==================== DU_A_UNIT — CHEMISTRY ====================
  {
    examType: "DU_A_UNIT",
    subject: "CHEMISTRY",
    text: "একটি দ্রবণের pH = 3 হলে [H⁺] কত?",
    options: ["10⁻³ M", "10³ M", "3 M", "10⁻¹¹ M"],
    correctAnswer: "10⁻³ M",
    explanation: "pH = −log[H⁺], তাই [H⁺] = 10⁻³ M।",
    difficulty: "MEDIUM",
  },
  {
    examType: "DU_A_UNIT",
    subject: "CHEMISTRY",
    text: "কোনটি প্রতিস্থাপন বিক্রিয়ার উদাহরণ?",
    options: ["CH₄ + Cl₂ → CH₃Cl + HCl", "C₂H₄ + H₂ → C₂H₆", "CaCO₃ → CaO + CO₂", "2H₂ + O₂ → 2H₂O"],
    correctAnswer: "CH₄ + Cl₂ → CH₃Cl + HCl",
    explanation: "অ্যালকেনে হ্যালোজেন প্রতিস্থাপন বিক্রিয়া ঘটে।",
    difficulty: "MEDIUM",
  },
  {
    examType: "DU_A_UNIT",
    subject: "CHEMISTRY",
    text: "ইলেকট্রন বিন্যাস 1s² 2s² 2p⁶ 3s¹ কোন মৌলের?",
    options: ["সোডিয়াম", "ম্যাগনেসিয়াম", "নিয়ন", "পটাশিয়াম"],
    correctAnswer: "সোডিয়াম",
    explanation: "মোট ১১টি ইলেকট্রন — পারমাণবিক সংখ্যা ১১ = সোডিয়াম।",
    difficulty: "MEDIUM",
  },
  {
    examType: "DU_A_UNIT",
    subject: "CHEMISTRY",
    text: "বাফার দ্রবণ কী করে?",
    options: ["pH প্রায় স্থির রাখে", "pH বাড়ায়", "pH কমায়", "দ্রবণ রঙিন করে"],
    correctAnswer: "pH প্রায় স্থির রাখে",
    explanation: "দুর্বল অ্যাসিড ও তার লবণের মিশ্রণ অল্প অ্যাসিড/ক্ষার যোগেও pH ধরে রাখে।",
    difficulty: "MEDIUM",
  },
  {
    examType: "DU_A_UNIT",
    subject: "CHEMISTRY",
    text: "কোনটি সমাণুতা (isomerism) দেখায়?",
    options: ["C₄H₁₀", "CH₄", "C₂H₆", "H₂O"],
    correctAnswer: "C₄H₁₀",
    explanation: "বিউটেনের দুটি গাঠনিক সমাণু আছে — n-বিউটেন ও আইসোবিউটেন।",
    difficulty: "HARD",
  },
  {
    examType: "DU_A_UNIT",
    subject: "CHEMISTRY",
    text: "গ্যালভানিক কোষে অ্যানোডে কী ঘটে?",
    options: ["জারণ", "বিজারণ", "কোনো বিক্রিয়া নয়", "তড়িৎ বিশ্লেষণ"],
    correctAnswer: "জারণ",
    explanation: "গ্যালভানিক কোষে অ্যানোড ঋণাত্মক; সেখানে জারণ ঘটে ও ইলেকট্রন নির্গত হয়।",
    difficulty: "HARD",
  },
  {
    examType: "DU_A_UNIT",
    subject: "CHEMISTRY",
    text: "১ মোল CO₂ এর ভর কত গ্রাম?",
    options: ["44 g", "28 g", "32 g", "12 g"],
    correctAnswer: "44 g",
    explanation: "C(12) + 2×O(16) = 44 g/mol।",
    difficulty: "EASY",
  },
  {
    examType: "DU_A_UNIT",
    subject: "CHEMISTRY",
    text: "কোনটি সবচেয়ে সক্রিয় ধাতু?",
    options: ["পটাশিয়াম", "লোহা", "তামা", "সোনা"],
    correctAnswer: "পটাশিয়াম",
    explanation: "সক্রিয়তা সিরিজে পটাশিয়াম শীর্ষের দিকে; পানির সাথেও তীব্র বিক্রিয়া করে।",
    difficulty: "MEDIUM",
  },
  {
    examType: "DU_A_UNIT",
    subject: "CHEMISTRY",
    text: "জারণ সংখ্যা H₂SO₄ এ সালফারের কত?",
    options: ["+6", "+4", "+2", "−2"],
    correctAnswer: "+6",
    explanation: "2(+1) + S + 4(−2) = 0 → S = +6।",
    difficulty: "HARD",
  },
  {
    examType: "DU_A_UNIT",
    subject: "CHEMISTRY",
    text: "কোনটি অ্যালডিহাইড কার্যকরী মূলক?",
    options: ["−CHO", "−COOH", "−OH", "−CO−"],
    correctAnswer: "−CHO",
    explanation: "অ্যালডিহাইডে কার্বনিল কার্বনের সাথে অন্তত একটি হাইড্রোজেন যুক্ত থাকে।",
    difficulty: "MEDIUM",
  },
  {
    examType: "DU_A_UNIT",
    subject: "CHEMISTRY",
    text: "এনট্রপি (S) কী নির্দেশ করে?",
    options: ["বিশৃঙ্খলার মাত্রা", "তাপমাত্রা", "চাপ", "আয়তন"],
    correctAnswer: "বিশৃঙ্খলার মাত্রা",
    explanation: "এনট্রপি সিস্টেমের অবিন্যস্ততা বা এলোমেলোতার পরিমাপ।",
    difficulty: "MEDIUM",
  },

  // ==================== DU_A_UNIT — MATH ====================
  {
    examType: "DU_A_UNIT",
    subject: "MATH",
    text: "d/dx (x⁴) = ?",
    options: ["4x³", "x³", "4x⁵", "3x⁴"],
    correctAnswer: "4x³",
    explanation: "ঘাত সূত্র: d/dx(xⁿ) = n·xⁿ⁻¹।",
    difficulty: "EASY",
  },
  {
    examType: "DU_A_UNIT",
    subject: "MATH",
    text: "∫ cos x dx = ?",
    options: ["sin x + C", "−sin x + C", "cos x + C", "tan x + C"],
    correctAnswer: "sin x + C",
    explanation: "cos x এর অবিচ্ছেদ sin x।",
    difficulty: "EASY",
  },
  {
    examType: "DU_A_UNIT",
    subject: "MATH",
    text: "log₂ 32 = ?",
    options: ["5", "6", "4", "8"],
    correctAnswer: "5",
    explanation: "2⁵ = 32, তাই log₂32 = 5।",
    difficulty: "EASY",
  },
  {
    examType: "DU_A_UNIT",
    subject: "MATH",
    text: "একটি সমান্তর ধারার প্রথম পদ 3, সাধারণ অন্তর 4 হলে ১০ম পদ কত?",
    options: ["39", "40", "36", "43"],
    correctAnswer: "39",
    explanation: "aₙ = a + (n−1)d = 3 + 9×4 = 39।",
    difficulty: "MEDIUM",
  },
  {
    examType: "DU_A_UNIT",
    subject: "MATH",
    text: "(1+x)ⁿ এর বিস্তৃতিতে পদসংখ্যা কত?",
    options: ["n+1", "n", "n−1", "2n"],
    correctAnswer: "n+1",
    explanation: "দ্বিপদী বিস্তৃতিতে মোট (n+1) টি পদ থাকে।",
    difficulty: "MEDIUM",
  },
  {
    examType: "DU_A_UNIT",
    subject: "MATH",
    text: "দুটি ঘটনার সম্ভাবনা P(A)=0.5, P(B)=0.4, স্বাধীন হলে P(A∩B) = ?",
    options: ["0.2", "0.9", "0.1", "0.45"],
    correctAnswer: "0.2",
    explanation: "স্বাধীন ঘটনায় P(A∩B) = P(A)×P(B) = 0.5×0.4 = 0.2।",
    difficulty: "MEDIUM",
  },
  {
    examType: "DU_A_UNIT",
    subject: "MATH",
    text: "একটি বৃত্তের ব্যাসার্ধ r হলে ক্ষেত্রফল কত?",
    options: ["πr²", "2πr", "πr", "4πr²"],
    correctAnswer: "πr²",
    explanation: "বৃত্তের ক্ষেত্রফল πr², পরিধি 2πr।",
    difficulty: "EASY",
  },
  {
    examType: "DU_A_UNIT",
    subject: "MATH",
    text: "tan 45° এর মান কত?",
    options: ["1", "0", "√3", "1/√3"],
    correctAnswer: "1",
    explanation: "tan 45° = sin45/cos45 = 1।",
    difficulty: "EASY",
  },
  {
    examType: "DU_A_UNIT",
    subject: "MATH",
    text: "একটি ২×২ ম্যাট্রিক্স [[2,3],[1,4]] এর নির্ণায়ক কত?",
    options: ["5", "11", "8", "2"],
    correctAnswer: "5",
    explanation: "det = (2×4) − (3×1) = 8 − 3 = 5।",
    difficulty: "MEDIUM",
  },
  {
    examType: "DU_A_UNIT",
    subject: "MATH",
    text: "lim(x→2) (x²−4)/(x−2) = ?",
    options: ["4", "0", "2", "অসংজ্ঞায়িত"],
    correctAnswer: "4",
    explanation: "(x²−4)/(x−2) = x+2, x→2 এ মান 4।",
    difficulty: "MEDIUM",
  },
  {
    examType: "DU_A_UNIT",
    subject: "MATH",
    text: "একটি সরলরেখার ঢাল m ও y-অন্তঃখণ্ড c হলে সমীকরণ কী?",
    options: ["y = mx + c", "x = my + c", "y = mx − c", "y = c/m"],
    correctAnswer: "y = mx + c",
    explanation: "ঢাল-অন্তঃখণ্ড আকারে সরলরেখার সমীকরণ।",
    difficulty: "EASY",
  },

  // ==================== DU_A_UNIT — BIOLOGY ====================
  {
    examType: "DU_A_UNIT",
    subject: "BIOLOGY",
    text: "উদ্ভিদের পরিবহন কলা কোনগুলো?",
    options: ["জাইলেম ও ফ্লোয়েম", "প্যারেনকাইমা ও কোলেনকাইমা", "এপিডার্মিস", "ক্যাম্বিয়াম"],
    correctAnswer: "জাইলেম ও ফ্লোয়েম",
    explanation: "জাইলেম পানি, ফ্লোয়েম খাদ্য পরিবহন করে।",
    difficulty: "EASY",
  },
  {
    examType: "DU_A_UNIT",
    subject: "BIOLOGY",
    text: "DNA এর দ্বি-হেলিক্স মডেল কে দেন?",
    options: ["ওয়াটসন ও ক্রিক", "মেন্ডেল", "ডারউইন", "পাস্তুর"],
    correctAnswer: "ওয়াটসন ও ক্রিক",
    explanation: "১৯৫৩ সালে জেমস ওয়াটসন ও ফ্রান্সিস ক্রিক মডেলটি প্রস্তাব করেন।",
    difficulty: "EASY",
  },
  {
    examType: "DU_A_UNIT",
    subject: "BIOLOGY",
    text: "মিয়োসিস বিভাজনের ফল কী?",
    options: ["ক্রোমোজোম সংখ্যা অর্ধেক হয়", "ক্রোমোজোম সংখ্যা দ্বিগুণ হয়", "অপরিবর্তিত থাকে", "কোষ মারা যায়"],
    correctAnswer: "ক্রোমোজোম সংখ্যা অর্ধেক হয়",
    explanation: "মিয়োসিসে ডিপ্লয়েড কোষ থেকে ৪টি হ্যাপ্লয়েড গ্যামেট তৈরি হয়।",
    difficulty: "MEDIUM",
  },
  {
    examType: "DU_A_UNIT",
    subject: "BIOLOGY",
    text: "ব্যাকটেরিয়ার কোষপ্রাচীর কী দিয়ে গঠিত?",
    options: ["পেপটাইডোগ্লাইক্যান", "সেলুলোজ", "কাইটিন", "লিপিড"],
    correctAnswer: "পেপটাইডোগ্লাইক্যান",
    explanation: "ব্যাকটেরিয়ার কোষপ্রাচীরের প্রধান উপাদান পেপটাইডোগ্লাইক্যান (মিউরিন)।",
    difficulty: "HARD",
  },
  {
    examType: "DU_A_UNIT",
    subject: "BIOLOGY",
    text: "সালোকসংশ্লেষণের অন্ধকার পর্যায় কোথায় ঘটে?",
    options: ["স্ট্রোমা", "গ্রানা", "থাইলাকয়েড", "কোষপ্রাচীর"],
    correctAnswer: "স্ট্রোমা",
    explanation: "ক্যালভিন চক্র ক্লোরোপ্লাস্টের স্ট্রোমায় সম্পন্ন হয়।",
    difficulty: "HARD",
  },
  {
    examType: "DU_A_UNIT",
    subject: "BIOLOGY",
    text: "কোনটি বহুকোষী শৈবাল নয়?",
    options: ["ক্ল্যামাইডোমোনাস", "স্পাইরোগাইরা", "আলভা", "স্যারগাসাম"],
    correctAnswer: "ক্ল্যামাইডোমোনাস",
    explanation: "ক্ল্যামাইডোমোনাস এককোষী সবুজ শৈবাল।",
    difficulty: "HARD",
  },
  {
    examType: "DU_A_UNIT",
    subject: "BIOLOGY",
    text: "মানুষের লিঙ্গ নির্ধারণকারী ক্রোমোজোম কোনটি?",
    options: ["Y ক্রোমোজোম", "X ক্রোমোজোম", "২১ নং", "১৮ নং"],
    correctAnswer: "Y ক্রোমোজোম",
    explanation: "Y ক্রোমোজোমের SRY জিন পুরুষ লিঙ্গ নির্ধারণ করে।",
    difficulty: "MEDIUM",
  },
  {
    examType: "DU_A_UNIT",
    subject: "BIOLOGY",
    text: "এনজাইম মূলত কী?",
    options: ["প্রোটিন", "কার্বোহাইড্রেট", "লিপিড", "নিউক্লিক অ্যাসিড"],
    correctAnswer: "প্রোটিন",
    explanation: "অধিকাংশ এনজাইম প্রোটিন; কিছু RNA (রাইবোজাইম) ব্যতিক্রম।",
    difficulty: "EASY",
  },
  {
    examType: "DU_A_UNIT",
    subject: "BIOLOGY",
    text: "স্নায়ুকোষের যে অংশ সংকেত গ্রহণ করে তার নাম কী?",
    options: ["ডেনড্রাইট", "অ্যাক্সন", "সাইন্যাপস", "মায়েলিন"],
    correctAnswer: "ডেনড্রাইট",
    explanation: "ডেনড্রাইট অন্য নিউরন থেকে সংকেত গ্রহণ করে কোষদেহে পাঠায়।",
    difficulty: "MEDIUM",
  },
  {
    examType: "DU_A_UNIT",
    subject: "BIOLOGY",
    text: "ইকোসিস্টেমে শক্তির প্রবাহ কেমন?",
    options: ["একমুখী", "দ্বিমুখী", "চক্রাকার", "এলোমেলো"],
    correctAnswer: "একমুখী",
    explanation: "সূর্য → উৎপাদক → খাদক — শক্তি একমুখী, কিন্তু পুষ্টি উপাদান চক্রাকারে ঘোরে।",
    difficulty: "MEDIUM",
  },
  {
    examType: "DU_A_UNIT",
    subject: "BIOLOGY",
    text: "কোন উদ্ভিদে সালোকসংশ্লেষণে C4 পথ দেখা যায়?",
    options: ["ভুট্টা", "ধান", "গম", "আলু"],
    correctAnswer: "ভুট্টা",
    explanation: "ভুট্টা, আখ ইত্যাদি C4 উদ্ভিদ — উচ্চ তাপে দক্ষভাবে CO₂ ধরে।",
    difficulty: "HARD",
  },

  // ==================== BUET — MATH ====================
  {
    examType: "BUET",
    subject: "MATH",
    text: "∫₀¹ x² dx = ?",
    options: ["1/3", "1/2", "1", "2/3"],
    correctAnswer: "1/3",
    explanation: "[x³/3]₀¹ = 1/3।",
    difficulty: "MEDIUM",
  },
  {
    examType: "BUET",
    subject: "MATH",
    text: "d/dx (sin x · cos x) = ?",
    options: ["cos 2x", "−sin 2x", "sin 2x", "2cos x"],
    correctAnswer: "cos 2x",
    explanation: "sin x·cos x = (1/2)sin2x; অন্তরকলন = cos2x।",
    difficulty: "HARD",
  },
  {
    examType: "BUET",
    subject: "MATH",
    text: "একটি সমীকরণ x² − 5x + 6 = 0 এর মূলদ্বয়ের গুণফল কত?",
    options: ["6", "5", "−6", "1"],
    correctAnswer: "6",
    explanation: "ax²+bx+c=0 এ মূলের গুণফল = c/a = 6।",
    difficulty: "MEDIUM",
  },
  {
    examType: "BUET",
    subject: "MATH",
    text: "ভেক্টর A = 3î + 4ĵ এর মান কত?",
    options: ["5", "7", "12", "25"],
    correctAnswer: "5",
    explanation: "|A| = √(3²+4²) = √25 = 5।",
    difficulty: "EASY",
  },
  {
    examType: "BUET",
    subject: "MATH",
    text: "(x+2)⁵ বিস্তৃতিতে x³ এর সহগ কত?",
    options: ["40", "80", "10", "32"],
    correctAnswer: "40",
    explanation: "C(5,2)·2² = 10×4 = 40।",
    difficulty: "HARD",
  },
  {
    examType: "BUET",
    subject: "MATH",
    text: "একটি গুণোত্তর ধারার প্রথম পদ 2, সাধারণ অনুপাত 3, ৫ম পদ কত?",
    options: ["162", "54", "243", "96"],
    correctAnswer: "162",
    explanation: "aₙ = ar^(n−1) = 2×3⁴ = 162।",
    difficulty: "MEDIUM",
  },
  {
    examType: "BUET",
    subject: "MATH",
    text: "cos 2θ = ?",
    options: ["2cos²θ − 1", "2sin²θ − 1", "1 − 2cos²θ", "cos²θ + sin²θ"],
    correctAnswer: "2cos²θ − 1",
    explanation: "দ্বিগুণ কোণের সূত্র; সমতুল্য রূপ 1 − 2sin²θ।",
    difficulty: "MEDIUM",
  },
  {
    examType: "BUET",
    subject: "MATH",
    text: "একটি অধিবৃত্ত y² = 4ax এর উপকেন্দ্র কোথায়?",
    options: ["(a, 0)", "(0, a)", "(−a, 0)", "(0, 0)"],
    correctAnswer: "(a, 0)",
    explanation: "y² = 4ax এর উপকেন্দ্র (a,0), নিয়ামক x = −a।",
    difficulty: "HARD",
  },
  {
    examType: "BUET",
    subject: "MATH",
    text: "∑(n=1 থেকে 10) n = ?",
    options: ["55", "50", "100", "45"],
    correctAnswer: "55",
    explanation: "n(n+1)/2 = 10×11/2 = 55।",
    difficulty: "EASY",
  },
  {
    examType: "BUET",
    subject: "MATH",
    text: "একটি ফাংশন f(x) = x² এর x = 3 বিন্দুতে স্পর্শকের ঢাল কত?",
    options: ["6", "9", "3", "1"],
    correctAnswer: "6",
    explanation: "f′(x) = 2x, x=3 এ ঢাল = 6।",
    difficulty: "MEDIUM",
  },
  {
    examType: "BUET",
    subject: "MATH",
    text: "i² এর মান কত? (i = জটিল একক)",
    options: ["−1", "1", "0", "i"],
    correctAnswer: "−1",
    explanation: "জটিল সংখ্যার সংজ্ঞা অনুযায়ী i = √(−1), তাই i² = −1।",
    difficulty: "EASY",
  },
  {
    examType: "BUET",
    subject: "MATH",
    text: "৫ জন থেকে ৩ জন বাছাই করার উপায় কত?",
    options: ["10", "60", "15", "20"],
    correctAnswer: "10",
    explanation: "সমাবেশে বাছাইয়ের ক্রম গুরুত্বপূর্ণ নয়। তাই C(5,3) = 5!/(3!×2!) = (5×4)/(2×1) = 10 উপায়।",
    difficulty: "MEDIUM",
  },
  {
    examType: "BUET",
    subject: "MATH",
    text: "একটি সরলরেখা 2x + 3y = 6 এর ঢাল কত?",
    options: ["−2/3", "2/3", "3/2", "−3/2"],
    correctAnswer: "−2/3",
    explanation: "y = (6−2x)/3 = 2 − (2/3)x, ঢাল = −2/3।",
    difficulty: "MEDIUM",
  },
  {
    examType: "BUET",
    subject: "MATH",
    text: "∫ (1/x) dx = ?",
    options: ["ln|x| + C", "x²/2 + C", "−1/x² + C", "1/x + C"],
    correctAnswer: "ln|x| + C",
    explanation: "1/x এর অবিচ্ছেদ প্রাকৃতিক লগারিদম।",
    difficulty: "MEDIUM",
  },
  {
    examType: "BUET",
    subject: "MATH",
    text: "sin 30° + cos 60° = ?",
    options: ["1", "0.5", "1.5", "0"],
    correctAnswer: "1",
    explanation: "sin30° = 0.5, cos60° = 0.5, যোগফল = 1।",
    difficulty: "EASY",
  },
  {
    examType: "BUET",
    subject: "MATH",
    text: "একটি ৩×৩ একক ম্যাট্রিক্সের নির্ণায়ক কত?",
    options: ["1", "0", "3", "9"],
    correctAnswer: "1",
    explanation: "একক ম্যাট্রিক্সের নির্ণায়ক সর্বদা ১।",
    difficulty: "MEDIUM",
  },

  // ==================== BUET — PHYSICS ====================
  {
    examType: "BUET",
    subject: "PHYSICS",
    text: "একটি 2 kg বস্তুতে 10 N বল প্রয়োগে ত্বরণ কত?",
    options: ["5 m/s²", "20 m/s²", "0.2 m/s²", "12 m/s²"],
    correctAnswer: "5 m/s²",
    explanation: "a = F/m = 10/2 = 5 m/s²।",
    difficulty: "EASY",
  },
  {
    examType: "BUET",
    subject: "PHYSICS",
    text: "কৌণিক বেগের একক কী?",
    options: ["rad/s", "m/s", "rad", "s⁻²"],
    correctAnswer: "rad/s",
    explanation: "কৌণিক বেগ ω = θ/t, একক রেডিয়ান প্রতি সেকেন্ড।",
    difficulty: "EASY",
  },
  {
    examType: "BUET",
    subject: "PHYSICS",
    text: "একটি বস্তুর গতিশক্তি দ্বিগুণ করতে বেগ কত গুণ করতে হবে?",
    options: ["√2 গুণ", "2 গুণ", "4 গুণ", "1/2 গুণ"],
    correctAnswer: "√2 গুণ",
    explanation: "KE = ½mv², KE দ্বিগুণ হলে v হবে √2 গুণ।",
    difficulty: "HARD",
  },
  {
    examType: "BUET",
    subject: "PHYSICS",
    text: "ইয়ং এর গুণাঙ্কের একক কী?",
    options: ["N/m²", "N/m", "N·m", "N"],
    correctAnswer: "N/m²",
    explanation: "ইয়ং গুণাঙ্ক = পীড়ন/বিকৃতি; বিকৃতি মাত্রাহীন, তাই একক পীড়নের মতো N/m² (Pa)।",
    difficulty: "MEDIUM",
  },
  {
    examType: "BUET",
    subject: "PHYSICS",
    text: "একটি ট্রান্সফরমারে কী রূপান্তরিত হয়?",
    options: ["বিভব", "কম্পাঙ্ক", "ক্ষমতা", "আধান"],
    correctAnswer: "বিভব",
    explanation: "ট্রান্সফরমার AC বিভব বাড়ায়/কমায়; কম্পাঙ্ক অপরিবর্তিত থাকে।",
    difficulty: "MEDIUM",
  },
  {
    examType: "BUET",
    subject: "PHYSICS",
    text: "আর্কিমিডিসের সূত্র কী নিয়ে?",
    options: ["প্লবতা", "জড়তা", "ঘর্ষণ", "স্থিতিস্থাপকতা"],
    correctAnswer: "প্লবতা",
    explanation: "নিমজ্জিত বস্তু অপসারিত তরলের ওজনের সমান ঊর্ধ্বমুখী বল পায়।",
    difficulty: "EASY",
  },
  {
    examType: "BUET",
    subject: "PHYSICS",
    text: "বেগ-সময় লেখচিত্রের ঢাল কী নির্দেশ করে?",
    options: ["ত্বরণ", "সরণ", "দূরত্ব", "বল"],
    correctAnswer: "ত্বরণ",
    explanation: "v-t গ্রাফের ঢাল = dv/dt = ত্বরণ; ক্ষেত্রফল = সরণ।",
    difficulty: "MEDIUM",
  },
  {
    examType: "BUET",
    subject: "PHYSICS",
    text: "একটি ফোটনের শক্তি কীসের সমানুপাতিক?",
    options: ["কম্পাঙ্কের", "তরঙ্গদৈর্ঘ্যের", "বিস্তারের", "বেগের"],
    correctAnswer: "কম্পাঙ্কের",
    explanation: "E = hf — শক্তি কম্পাঙ্কের সমানুপাতিক, তরঙ্গদৈর্ঘ্যের ব্যস্তানুপাতিক।",
    difficulty: "MEDIUM",
  },
  {
    examType: "BUET",
    subject: "PHYSICS",
    text: "সমান্তরাল প্লেট ক্যাপাসিটরের ধারকত্ব কীসের উপর নির্ভর করে না?",
    options: ["আধানের পরিমাণ", "প্লেটের ক্ষেত্রফল", "প্লেটের দূরত্ব", "মাধ্যমের প্রকৃতি"],
    correctAnswer: "আধানের পরিমাণ",
    explanation: "C = ε₀A/d — জ্যামিতি ও মাধ্যমের উপর নির্ভরশীল, আধানের উপর নয়।",
    difficulty: "HARD",
  },
  {
    examType: "BUET",
    subject: "PHYSICS",
    text: "কেপলারের তৃতীয় সূত্র অনুযায়ী T² ∝ ?",
    options: ["r³", "r²", "r", "1/r"],
    correctAnswer: "r³",
    explanation: "পর্যায়কালের বর্গ কক্ষপথের গড় ব্যাসার্ধের ঘনের সমানুপাতিক।",
    difficulty: "HARD",
  },
  {
    examType: "BUET",
    subject: "PHYSICS",
    text: "আলোর ব্যতিচার কী প্রমাণ করে?",
    options: ["আলোর তরঙ্গ ধর্ম", "আলোর কণা ধর্ম", "আলোর বেগ", "আলোর রঙ"],
    correctAnswer: "আলোর তরঙ্গ ধর্ম",
    explanation: "ইয়ংয়ের দ্বি-চিড় পরীক্ষা আলোর তরঙ্গ প্রকৃতি প্রমাণ করে।",
    difficulty: "MEDIUM",
  },
  {
    examType: "BUET",
    subject: "PHYSICS",
    text: "১ অশ্বক্ষমতা প্রায় কত ওয়াট?",
    options: ["746 W", "1000 W", "550 W", "100 W"],
    correctAnswer: "746 W",
    explanation: "১ HP ≈ ৭৪৬ ওয়াট।",
    difficulty: "MEDIUM",
  },
  {
    examType: "BUET",
    subject: "PHYSICS",
    text: "তাপ পরিবাহিতার একক কী?",
    options: ["W/m·K", "J/kg", "W/m²", "J/K"],
    correctAnswer: "W/m·K",
    explanation: "তাপ পরিবাহিতাঙ্ক k এর একক ওয়াট প্রতি মিটার প্রতি কেলভিন।",
    difficulty: "HARD",
  },
  {
    examType: "BUET",
    subject: "PHYSICS",
    text: "একটি বস্তু বৃত্তাকার পথে ঘুরলে কোন বল কেন্দ্রমুখী?",
    options: ["কেন্দ্রাভিমুখী বল", "কেন্দ্রবিমুখী বল", "ঘর্ষণ বল", "অভিকর্ষ বল"],
    correctAnswer: "কেন্দ্রাভিমুখী বল",
    explanation: "F = mv²/r কেন্দ্রের দিকে ক্রিয়া করে বস্তুকে বৃত্তপথে রাখে।",
    difficulty: "MEDIUM",
  },
  {
    examType: "BUET",
    subject: "PHYSICS",
    text: "ডায়োড কোন কাজে ব্যবহৃত হয়?",
    options: ["একমুখীকরণ", "বিবর্ধন", "দোলন", "রোধ বৃদ্ধি"],
    correctAnswer: "একমুখীকরণ",
    explanation: "ডায়োড একদিকে প্রবাহ চালায়, তাই AC কে DC তে রূপান্তরে (rectifier) ব্যবহৃত।",
    difficulty: "MEDIUM",
  },
  {
    examType: "BUET",
    subject: "PHYSICS",
    text: "শব্দের তীব্রতার একক কী?",
    options: ["ডেসিবেল", "হার্জ", "ওয়াট", "প্যাসকেল"],
    correctAnswer: "ডেসিবেল",
    explanation: "শব্দের তীব্রতা স্তর লগারিদমিক স্কেলে ডেসিবেল (dB) এ মাপা হয়।",
    difficulty: "EASY",
  },
  {
    examType: "BUET",
    subject: "PHYSICS",
    text: "আপেক্ষিক গুরুত্ব কী?",
    options: ["পানির ঘনত্বের সাপেক্ষে ঘনত্বের অনুপাত", "ভর", "ওজন", "আয়তন"],
    correctAnswer: "পানির ঘনত্বের সাপেক্ষে ঘনত্বের অনুপাত",
    explanation: "আপেক্ষিক গুরুত্ব মাত্রাহীন; ৪°C এর পানিকে আদর্শ ধরা হয়।",
    difficulty: "MEDIUM",
  },

  // ==================== BUET — CHEMISTRY ====================
  {
    examType: "BUET",
    subject: "CHEMISTRY",
    text: "হাইড্রোজেন বন্ধন কোন যৌগে সবচেয়ে শক্তিশালী?",
    options: ["HF", "HCl", "HBr", "HI"],
    correctAnswer: "HF",
    explanation: "ফ্লোরিনের উচ্চ তড়িৎ-ঋণাত্মকতা HF এ সবচেয়ে শক্তিশালী হাইড্রোজেন বন্ধন দেয়।",
    difficulty: "HARD",
  },
  {
    examType: "BUET",
    subject: "CHEMISTRY",
    text: "একটি বিক্রিয়ার হার কীসের উপর নির্ভর করে না?",
    options: ["মোট আয়তন", "তাপমাত্রা", "ঘনমাত্রা", "প্রভাবক"],
    correctAnswer: "মোট আয়তন",
    explanation: "হার ঘনমাত্রা, তাপমাত্রা, প্রভাবক ও পৃষ্ঠতলের উপর নির্ভরশীল।",
    difficulty: "MEDIUM",
  },
  {
    examType: "BUET",
    subject: "CHEMISTRY",
    text: "কোনটি উভধর্মী অক্সাইড?",
    options: ["Al₂O₃", "Na₂O", "CO₂", "MgO"],
    correctAnswer: "Al₂O₃",
    explanation: "অ্যালুমিনিয়াম অক্সাইড অ্যাসিড ও ক্ষার উভয়ের সাথেই বিক্রিয়া করে।",
    difficulty: "HARD",
  },
  {
    examType: "BUET",
    subject: "CHEMISTRY",
    text: "ব্যাঞ্জিনের গঠনে কয়টি π ইলেকট্রন আছে?",
    options: ["6", "3", "12", "4"],
    correctAnswer: "6",
    explanation: "৩টি দ্বিবন্ধনে ৬টি π ইলেকট্রন — অনুরণনে বিস্তৃত হয়ে অ্যারোমেটিক স্থিতিশীলতা দেয়।",
    difficulty: "HARD",
  },
  {
    examType: "BUET",
    subject: "CHEMISTRY",
    text: "লা শাতেলিয়ার নীতি অনুযায়ী চাপ বাড়ালে বিক্রিয়া কোন দিকে সরে?",
    options: ["কম মোল সংখ্যার দিকে", "বেশি মোল সংখ্যার দিকে", "পরিবর্তন হয় না", "বিপরীত দিকে"],
    correctAnswer: "কম মোল সংখ্যার দিকে",
    explanation: "চাপ বাড়ালে সিস্টেম আয়তন কমানোর দিকে অর্থাৎ কম গ্যাস-মোলের দিকে সরে।",
    difficulty: "HARD",
  },
  {
    examType: "BUET",
    subject: "CHEMISTRY",
    text: "একটি দ্রবণের মোলারিটি কী?",
    options: ["প্রতি লিটার দ্রবণে মোল সংখ্যা", "প্রতি কেজি দ্রাবকে মোল", "শতকরা ভর", "মোট ভর"],
    correctAnswer: "প্রতি লিটার দ্রবণে মোল সংখ্যা",
    explanation: "M = মোল/আয়তন(L); মোলালিটি হলো প্রতি কেজি দ্রাবকে মোল।",
    difficulty: "MEDIUM",
  },
  {
    examType: "BUET",
    subject: "CHEMISTRY",
    text: "কোনটি তড়িৎ বিশ্লেষ্য পদার্থ?",
    options: ["NaCl দ্রবণ", "চিনির দ্রবণ", "বেনজিন", "কেরোসিন"],
    correctAnswer: "NaCl দ্রবণ",
    explanation: "আয়নে বিয়োজিত হয়ে বিদ্যুৎ পরিবহন করে।",
    difficulty: "EASY",
  },
  {
    examType: "BUET",
    subject: "CHEMISTRY",
    text: "স্থির অনুপাত সূত্র কে দেন?",
    options: ["প্রুস্ত", "ডাল্টন", "আভোগাড্রো", "বয়েল"],
    correctAnswer: "প্রুস্ত",
    explanation: "জোসেফ প্রুস্তের সূত্র — একটি যৌগে উপাদানের ভর অনুপাত সর্বদা স্থির।",
    difficulty: "HARD",
  },
  {
    examType: "BUET",
    subject: "CHEMISTRY",
    text: "কোন প্রক্রিয়ায় অ্যামোনিয়া শিল্পে তৈরি হয়?",
    options: ["হেবার প্রক্রিয়া", "কনট্যাক্ট প্রক্রিয়া", "সলভে প্রক্রিয়া", "অসওয়াল্ড প্রক্রিয়া"],
    correctAnswer: "হেবার প্রক্রিয়া",
    explanation: "N₂ + 3H₂ ⇌ 2NH₃, লোহা প্রভাবক, উচ্চ চাপ ও তাপে।",
    difficulty: "MEDIUM",
  },
  {
    examType: "BUET",
    subject: "CHEMISTRY",
    text: "sp² সংকরায়নে বন্ধন কোণ কত?",
    options: ["120°", "109.5°", "180°", "90°"],
    correctAnswer: "120°",
    explanation: "sp² সংকরায়নে ত্রিকোণীয় সমতলীয় আকার, কোণ ১২০°।",
    difficulty: "HARD",
  },
  {
    examType: "BUET",
    subject: "CHEMISTRY",
    text: "কোনটি গ্রিনহাউস গ্যাস নয়?",
    options: ["নাইট্রোজেন", "মিথেন", "CO₂", "জলীয় বাষ্প"],
    correctAnswer: "নাইট্রোজেন",
    explanation: "N₂ দ্বিপরমাণুক সমযোজী অণু, ইনফ্রারেড শোষণ করে না।",
    difficulty: "MEDIUM",
  },
  {
    examType: "BUET",
    subject: "CHEMISTRY",
    text: "ফ্যারাডের প্রথম সূত্র কীসের সম্পর্ক দেখায়?",
    options: ["আধান ও নিঃসৃত ভর", "চাপ ও আয়তন", "তাপ ও কাজ", "বেগ ও ভর"],
    correctAnswer: "আধান ও নিঃসৃত ভর",
    explanation: "m ∝ Q — তড়িৎ বিশ্লেষণে নিঃসৃত ভর প্রবাহিত আধানের সমানুপাতিক।",
    difficulty: "HARD",
  },
  {
    examType: "BUET",
    subject: "CHEMISTRY",
    text: "একটি মৌলের পারমাণবিক সংখ্যা কী নির্দেশ করে?",
    options: ["প্রোটন সংখ্যা", "নিউট্রন সংখ্যা", "ভর সংখ্যা", "ইলেকট্রন শক্তিস্তর"],
    correctAnswer: "প্রোটন সংখ্যা",
    explanation: "পারমাণবিক সংখ্যা Z = নিউক্লিয়াসে প্রোটনের সংখ্যা।",
    difficulty: "EASY",
  },
  {
    examType: "BUET",
    subject: "CHEMISTRY",
    text: "কোনটি পলিমার?",
    options: ["পলিথিন", "ইথেন", "মিথানল", "অ্যাসিটোন"],
    correctAnswer: "পলিথিন",
    explanation: "পলিথিন ইথিলিন মনোমারের পুনরাবৃত্তিতে গঠিত পলিমার।",
    difficulty: "EASY",
  },
  {
    examType: "BUET",
    subject: "CHEMISTRY",
    text: "এন্থালপি পরিবর্তন ΔH ঋণাত্মক হলে বিক্রিয়াটি কী?",
    options: ["তাপোৎপাদী", "তাপহারী", "নিরপেক্ষ", "সাম্যাবস্থায়"],
    correctAnswer: "তাপোৎপাদী",
    explanation: "ΔH < 0 মানে সিস্টেম তাপ ত্যাগ করেছে।",
    difficulty: "MEDIUM",
  },
  {
    examType: "BUET",
    subject: "CHEMISTRY",
    text: "অ্যাসিড-ক্ষার প্রশমন বিক্রিয়ার উৎপাদ কী?",
    options: ["লবণ ও পানি", "শুধু লবণ", "শুধু পানি", "গ্যাস"],
    correctAnswer: "লবণ ও পানি",
    explanation: "HCl + NaOH → NaCl + H₂O।",
    difficulty: "EASY",
  },
  {
    examType: "BUET",
    subject: "CHEMISTRY",
    text: "জারণ-বিজারণ বিক্রিয়ায় বিজারক কী করে?",
    options: ["ইলেকট্রন দান করে", "ইলেকট্রন গ্রহণ করে", "প্রোটন দান করে", "অপরিবর্তিত থাকে"],
    correctAnswer: "ইলেকট্রন দান করে",
    explanation: "বিজারক নিজে জারিত হয়ে অন্যকে বিজারিত করে।",
    difficulty: "MEDIUM",
  },
  {
    examType: "BUET",
    subject: "CHEMISTRY",
    text: "কোন কোয়ান্টাম সংখ্যা অরবিটালের আকৃতি নির্দেশ করে?",
    options: ["দিগংশীয় (l)", "প্রধান (n)", "চৌম্বক (m)", "স্পিন (s)"],
    correctAnswer: "দিগংশীয় (l)",
    explanation: "l = 0,1,2,3 → s, p, d, f অরবিটালের আকৃতি নির্ধারণ করে।",
    difficulty: "HARD",
  },
];

async function main() {
  console.log("🌱 Admission Prep প্রশ্ন (সেট ২) সিড করা শুরু হচ্ছে...");

  // ইতিমধ্যে থাকা প্রশ্নের text সংগ্রহ — ডুপ্লিকেট এড়াতে
  const existing = await prisma.admissionQuestion.findMany({ select: { text: true } });
  const existingTexts = new Set(existing.map((q) => q.text.trim()));

  const fresh = questions.filter((q) => !existingTexts.has(q.text.trim()));
  const skipped = questions.length - fresh.length;

  if (fresh.length === 0) {
    console.log("ℹ️  সব প্রশ্ন ইতিমধ্যে আছে — নতুন কিছু যোগ করা হয়নি।");
  } else {
    await prisma.admissionQuestion.createMany({
      data: fresh.map((q) => ({
        examType: q.examType,
        subject: q.subject,
        text: q.text,
        options: q.options,
        correctAnswer: q.correctAnswer,
        explanation: q.explanation,
        difficulty: q.difficulty,
      })),
    });
    console.log(`✅ ${fresh.length}টা নতুন প্রশ্ন যোগ করা হয়েছে`);
  }
  if (skipped > 0) console.log(`⏭️  ${skipped}টা আগে থেকেই ছিল, স্কিপ করা হয়েছে`);

  // সারসংক্ষেপ — কনফিগের চাহিদার সাথে তুলনা
  const target: Record<string, Record<string, number>> = {
    MEDICAL: { BIOLOGY: 30, CHEMISTRY: 25, PHYSICS: 15, ENGLISH: 15, GENERAL_KNOWLEDGE: 15 },
    DU_A_UNIT: { PHYSICS: 15, CHEMISTRY: 15, MATH: 15, BIOLOGY: 15 },
    BUET: { MATH: 20, PHYSICS: 20, CHEMISTRY: 20 },
  };
  const rows = await prisma.admissionQuestion.groupBy({
    by: ["examType", "subject"],
    _count: true,
  });
  const have = new Map(rows.map((r) => [`${r.examType}/${r.subject}`, r._count]));

  console.log("\n📊 কভারেজ (আছে / দরকার):");
  let ok = true;
  for (const [exam, subs] of Object.entries(target)) {
    for (const [sub, need] of Object.entries(subs)) {
      const n = have.get(`${exam}/${sub}`) ?? 0;
      const mark = n >= need ? "✅" : "⚠️ ";
      if (n < need) ok = false;
      console.log(`  ${mark} ${exam} / ${sub}: ${n} / ${need}`);
    }
  }
  const total = rows.reduce((s, r) => s + r._count, 0);
  console.log(`\n  মোট প্রশ্ন: ${total}`);
  console.log(ok ? "  🎉 সব পরীক্ষার পূর্ণ কভারেজ হয়েছে!" : "  কিছু সাবজেক্টে এখনো ঘাটতি আছে।");
}

main()
  .catch((e) => {
    console.error("❌ Seed ব্যর্থ হয়েছে:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
