/**
 * Periodic Table Elements & HSC Chemistry Reference Data
 */

export interface PeriodicElement {
  number: number;
  symbol: string;
  nameBn: string;
  nameEn: string;
  mass: number;
  group: number;
  period: number;
  block: "s" | "p" | "d" | "f";
  category: "alkali" | "alkaline-earth" | "transition" | "post-transition" | "metalloid" | "nonmetal" | "halogen" | "noble-gas" | "lanthanide" | "actinide";
  electronConfig: string;
  electronegativity?: number;
  ionizationEnergy?: number; // kJ/mol
  oxidationStates?: string;
  hscFact: string;
}

export const PERIODIC_ELEMENTS: PeriodicElement[] = [
  {
    number: 1,
    symbol: "H",
    nameBn: "হাইড্রোজেন",
    nameEn: "Hydrogen",
    mass: 1.008,
    group: 1,
    period: 1,
    block: "s",
    category: "nonmetal",
    electronConfig: "1s¹",
    electronegativity: 2.2,
    ionizationEnergy: 1312,
    oxidationStates: "-1, +1",
    hscFact: "পর্যায় সারণিতে হাইড্রোজেনের অবস্থান বিতর্কিত (গ্রুপ ১ ক্ষার ধাতু ও গ্রুপ ১৭ হ্যালোজেন উভয়ের সাথেই সাদৃশ্যপূর্ণ)।",
  },
  {
    number: 2,
    symbol: "He",
    nameBn: "হিলিয়াম",
    nameEn: "Helium",
    mass: 4.0026,
    group: 18,
    period: 1,
    block: "s",
    category: "noble-gas",
    electronConfig: "1s²",
    ionizationEnergy: 2372,
    oxidationStates: "0",
    hscFact: "s-ব্লকভুক্ত হওয়া সত্ত্বেও নিষ্ক্রিয় গ্যাস হওয়ায় একে গ্রুপ ১৮-তে স্থান দেওয়া হয়েছে। এর প্রথম আয়নীকরণ শক্তি সবচেয়ে বেশি।",
  },
  {
    number: 3,
    symbol: "Li",
    nameBn: "লিথিয়াম",
    nameEn: "Lithium",
    mass: 6.94,
    group: 1,
    period: 2,
    block: "s",
    category: "alkali",
    electronConfig: "[He] 2s¹",
    electronegativity: 0.98,
    ionizationEnergy: 520,
    oxidationStates: "+1",
    hscFact: "সবচেয়ে হালকা ধাতু এবং তীব্র বিজারক। ম্যাগনেসিয়ামের সাথে কর্ণ সম্পর্ক (Diagonal Relationship) দেখায়।",
  },
  {
    number: 4,
    symbol: "Be",
    nameBn: "বেরিলিয়াম",
    nameEn: "Beryllium",
    mass: 9.0122,
    group: 2,
    period: 2,
    block: "s",
    category: "alkaline-earth",
    electronConfig: "[He] 2s²",
    electronegativity: 1.57,
    ionizationEnergy: 899,
    oxidationStates: "+2",
    hscFact: "ছোট আকারের কারণে সমযোজী যৌগ (যেমন BeCl₂) গঠন করে এবং অ্যালুমিনিয়ামের সাথে কর্ণ সম্পর্ক প্রদর্শন করে।",
  },
  {
    number: 5,
    symbol: "B",
    nameBn: "বোরন",
    nameEn: "Boron",
    mass: 10.81,
    group: 13,
    period: 2,
    block: "p",
    category: "metalloid",
    electronConfig: "[He] 2s² 2p¹",
    electronegativity: 2.04,
    ionizationEnergy: 800,
    oxidationStates: "+3",
    hscFact: "BF₃ যৌগ অষ্টক সংকোচন (Octet Incomplete) দেখায় এবং এটি একটি শক্তিশালী লুইস অ্যাসিড।",
  },
  {
    number: 6,
    symbol: "C",
    nameBn: "কার্বন",
    nameEn: "Carbon",
    mass: 12.011,
    group: 14,
    period: 2,
    block: "p",
    category: "nonmetal",
    electronConfig: "[He] 2s² 2p²",
    electronegativity: 2.55,
    ionizationEnergy: 1086,
    oxidationStates: "-4, +2, +4",
    hscFact: "ক্যাটেনেশন ধর্মের কারণে লক্ষ লক্ষ জৈব যৌগ তৈরি করতে পারে। sp³, sp², sp সংকরায়ন দেখায়।",
  },
  {
    number: 7,
    symbol: "N",
    nameBn: "নাইট্রোজেন",
    nameEn: "Nitrogen",
    mass: 14.007,
    group: 15,
    period: 2,
    block: "p",
    category: "nonmetal",
    electronConfig: "[He] 2s² 2p³",
    electronegativity: 3.04,
    ionizationEnergy: 1402,
    oxidationStates: "-3, +3, +5",
    hscFact: "2p উপস্তর অর্ধপূর্ণ (Half-filled) হওয়ায় এর ১ম আয়নীকরণ শক্তি অক্সিজেনের চেয়ে বেশি।",
  },
  {
    number: 8,
    symbol: "O",
    nameBn: "অক্সিজেন",
    nameEn: "Oxygen",
    mass: 15.999,
    group: 16,
    period: 2,
    block: "p",
    category: "nonmetal",
    electronConfig: "[He] 2s² 2p⁴",
    electronegativity: 3.44,
    ionizationEnergy: 1314,
    oxidationStates: "-2, -1",
    hscFact: "পর্যায় সারণির ২য় সর্বাধিক তড়িৎ ঋণাত্মক মৌল। পানির অণুতে হাইড্রোজেন বন্ধন গঠনের মূল কারণ।",
  },
  {
    number: 9,
    symbol: "F",
    nameBn: "ফ্লোরিন",
    nameEn: "Fluorine",
    mass: 18.998,
    group: 17,
    period: 2,
    block: "p",
    category: "halogen",
    electronConfig: "[He] 2s² 2p⁵",
    electronegativity: 3.98,
    ionizationEnergy: 1681,
    oxidationStates: "-1",
    hscFact: "পর্যায় সারণির সর্বোচ্চ তড়িৎ ঋণাত্মক (3.98) ও সবচেয়ে সক্রিয় অধাতু। ইলেকট্রন আসক্তি ক্লোরিনের চেয়ে কম।",
  },
  {
    number: 10,
    symbol: "Ne",
    nameBn: "নিয়ন",
    nameEn: "Neon",
    mass: 20.18,
    group: 18,
    period: 2,
    block: "p",
    category: "noble-gas",
    electronConfig: "[He] 2s² 2p⁶",
    ionizationEnergy: 2080,
    oxidationStates: "0",
    hscFact: "সম্পূর্ণ অষ্টক পূরণ থাকায় রাসায়নিকভাবে সম্পূর্ণ নিষ্ক্রিয়। নিয়ন সাইন বোর্ডে লাল-কমলা আলো দেয়।",
  },
  {
    number: 11,
    symbol: "Na",
    nameBn: "সোডিয়াম",
    nameEn: "Sodium",
    mass: 22.99,
    group: 1,
    period: 3,
    block: "s",
    category: "alkali",
    electronConfig: "[Ne] 3s¹",
    electronegativity: 0.93,
    ionizationEnergy: 496,
    oxidationStates: "+1",
    hscFact: "শিখা পরীক্ষায় সোনালী হলুদ শিখা প্রদর্শন করে। কেরোসিনের নিচে সংরক্ষণ করা হয়।",
  },
  {
    number: 12,
    symbol: "Mg",
    nameBn: "ম্যাগনেসিয়াম",
    nameEn: "Magnesium",
    mass: 24.305,
    group: 2,
    period: 3,
    block: "s",
    category: "alkaline-earth",
    electronConfig: "[Ne] 3s²",
    electronegativity: 1.31,
    ionizationEnergy: 738,
    oxidationStates: "+2",
    hscFact: "শিখা পরীক্ষায় কোনো বর্ণ দেখায় না কারণ এর ইলেকট্রন উত্তেজিত হতে অতিরিক্ত শক্তির প্রয়োজন হয়।",
  },
  {
    number: 13,
    symbol: "Al",
    nameBn: "অ্যালুমিনিয়াম",
    nameEn: "Aluminium",
    mass: 26.982,
    group: 13,
    period: 3,
    block: "p",
    category: "post-transition",
    electronConfig: "[Ne] 3s² 3p¹",
    electronegativity: 1.61,
    ionizationEnergy: 578,
    oxidationStates: "+3",
    hscFact: "Al₂O₃ একটি উভধর্মী (Amphoteric) অক্সাইড। AlCl₃ ডাইমার (Al₂Cl₆) আকারে অবস্থান করে।",
  },
  {
    number: 14,
    symbol: "Si",
    nameBn: "সিলিকন",
    nameEn: "Silicon",
    mass: 28.085,
    group: 14,
    period: 3,
    block: "p",
    category: "metalloid",
    electronConfig: "[Ne] 3s² 3p²",
    electronegativity: 1.9,
    ionizationEnergy: 786,
    oxidationStates: "-4, +4",
    hscFact: "SiO₂ একটি পলিমার বা বৃহৎ দৈত্যাকার অণু হওয়ায় এর গলনাঙ্ক ও স্ফুটনাঙ্ক অনেক বেশি।",
  },
  {
    number: 15,
    symbol: "P",
    nameBn: "ফসফরাস",
    nameEn: "Phosphorus",
    mass: 30.974,
    group: 15,
    period: 3,
    block: "p",
    category: "nonmetal",
    electronConfig: "[Ne] 3s² 3p³",
    electronegativity: 2.19,
    ionizationEnergy: 1012,
    oxidationStates: "-3, +3, +5",
    hscFact: "ফাঁকা 3d অরবিটাল থাকায় PCl₅ গঠন করতে পারে, কিন্তু নাইট্রোজেন NCl₅ গঠন করতে পারে না।",
  },
  {
    number: 16,
    symbol: "S",
    nameBn: "সালফার",
    nameEn: "Sulfur",
    mass: 32.06,
    group: 16,
    period: 3,
    block: "p",
    category: "nonmetal",
    electronConfig: "[Ne] 3s² 3p⁴",
    electronegativity: 2.58,
    ionizationEnergy: 1000,
    oxidationStates: "-2, +4, +6",
    hscFact: "SF₆ অষ্টক সম্প্রসারণ দেখায় এবং অষ্টতলকীয় আকৃতি ধারণ করে। স্পর্শ পদ্ধতিতে H₂SO₄ উৎপাদনে ব্যবহৃত।",
  },
  {
    number: 17,
    symbol: "Cl",
    nameBn: "ক্লোরিন",
    nameEn: "Chlorine",
    mass: 35.45,
    group: 17,
    period: 3,
    block: "p",
    category: "halogen",
    electronConfig: "[Ne] 3s² 3p⁵",
    electronegativity: 3.16,
    ionizationEnergy: 1251,
    oxidationStates: "-1, +1, +3, +5, +7",
    hscFact: "পর্যায় সারণির সর্বোচ্চ ইলেকট্রন আসক্তি (-349 kJ/mol) ক্লোরিনের (ফ্লোরিনের ইলেকট্রন ঘনত্বের বিকর্ষণের কারণে)।",
  },
  {
    number: 18,
    symbol: "Ar",
    nameBn: "আর্গন",
    nameEn: "Argon",
    mass: 39.948,
    group: 18,
    period: 3,
    block: "p",
    category: "noble-gas",
    electronConfig: "[Ne] 3s² 3p⁶",
    ionizationEnergy: 1520,
    oxidationStates: "0",
    hscFact: "বায়ুমণ্ডলে প্রাপ্ত নিষ্ক্রিয় গ্যাসগুলোর মধ্যে আর্গনের পরিমাণ সবচেয়ে বেশি (~0.93%)।",
  },
  {
    number: 19,
    symbol: "K",
    nameBn: "পটাশিয়াম",
    nameEn: "Potassium",
    mass: 39.098,
    group: 1,
    period: 4,
    block: "s",
    category: "alkali",
    electronConfig: "[Ar] 4s¹",
    electronegativity: 0.82,
    ionizationEnergy: 419,
    oxidationStates: "+1",
    hscFact: "আউফবাউ নীতি অনুসারে ১৯তম ইলেকট্রনটি 3d তে না গিয়ে 4s অরবিটালে আগে প্রবেশ করে। শিখায় বেগুনী বর্ণ দেয়।",
  },
  {
    number: 20,
    symbol: "Ca",
    nameBn: "ক্যালসিয়াম",
    nameEn: "Calcium",
    mass: 40.078,
    group: 2,
    period: 4,
    block: "s",
    category: "alkaline-earth",
    electronConfig: "[Ar] 4s²",
    electronegativity: 1.0,
    ionizationEnergy: 590,
    oxidationStates: "+2",
    hscFact: "শিখা পরীক্ষায় ইটের মতো লাল (Brick Red) শিখা প্রদর্শন করে।",
  },
  {
    number: 21,
    symbol: "Sc",
    nameBn: "স্ক্যান্ডিয়াম",
    nameEn: "Scandium",
    mass: 44.956,
    group: 3,
    period: 4,
    block: "d",
    category: "transition",
    electronConfig: "[Ar] 3d¹ 4s²",
    electronegativity: 1.36,
    ionizationEnergy: 633,
    oxidationStates: "+3",
    hscFact: "d-ব্লকভুক্ত হওয়া সত্ত্বেও অবস্থান্তর মৌল নয়, কারণ এর স্থায়ী আয়ন Sc³⁺ এ d-অরবিটাল সম্পূর্ণ ফাঁকা (3d⁰)।",
  },
  {
    number: 22,
    symbol: "Ti",
    nameBn: "টাইটানিয়াম",
    nameEn: "Titanium",
    mass: 47.867,
    group: 4,
    period: 4,
    block: "d",
    category: "transition",
    electronConfig: "[Ar] 3d² 4s²",
    electronegativity: 1.54,
    ionizationEnergy: 658,
    oxidationStates: "+2, +3, +4",
    hscFact: "অ্যারোপ্লেন ও মহাশূন্যযানের সংকর ধাতু তৈরিতে টাইটানিয়াম ব্যাপকভাবে ব্যবহৃত হয়।",
  },
  {
    number: 23,
    symbol: "V",
    nameBn: "ভ্যানাডিয়াম",
    nameEn: "Vanadium",
    mass: 50.942,
    group: 5,
    period: 4,
    block: "d",
    category: "transition",
    electronConfig: "[Ar] 3d³ 4s²",
    electronegativity: 1.63,
    ionizationEnergy: 650,
    oxidationStates: "+2, +3, +4, +5",
    hscFact: "V₂O₅ স্পর্শ পদ্ধতিতে সালফিউরিক এসিড তৈরির প্রধান প্রভাবক হিসেবে ব্যবহৃত হয়।",
  },
  {
    number: 24,
    symbol: "Cr",
    nameBn: "ক্রোমিয়াম",
    nameEn: "Chromium",
    mass: 51.996,
    group: 6,
    period: 4,
    block: "d",
    category: "transition",
    electronConfig: "[Ar] 3d⁵ 4s¹",
    electronegativity: 1.66,
    ionizationEnergy: 653,
    oxidationStates: "+2, +3, +6",
    hscFact: "আউফবাউ নীতির ব্যতিক্রম দেখায় (অর্ধপূর্ণ 3d⁵ অরবিটালের স্থায়িত্বের জন্য 4s² এর বদলে 4s¹ হয়)।",
  },
  {
    number: 25,
    symbol: "Mn",
    nameBn: "ম্যাঙ্গানিজ",
    nameEn: "Manganese",
    mass: 54.938,
    group: 7,
    period: 4,
    block: "d",
    category: "transition",
    electronConfig: "[Ar] 3d⁵ 4s²",
    electronegativity: 1.55,
    ionizationEnergy: 717,
    oxidationStates: "+2, +3, +4, +6, +7",
    hscFact: "সবচেয়ে বেশি সংখ্যক জারণ অবস্থা (+2 থেকে +7) প্রদর্শনকারী প্রথম সারির অবস্থান্তর ধাতু।",
  },
  {
    number: 26,
    symbol: "Fe",
    nameBn: "লোহা (আয়রন)",
    nameEn: "Iron",
    mass: 55.845,
    group: 8,
    period: 4,
    block: "d",
    category: "transition",
    electronConfig: "[Ar] 3d⁶ 4s²",
    electronegativity: 1.83,
    ionizationEnergy: 762,
    oxidationStates: "+2, +3",
    hscFact: "হেবার-বশ পদ্ধতিতে অ্যামোনিয়া উৎপাদনে সূক্ষ্ম আয়রন চূর্ণ প্রভাবক হিসেবে ব্যবহৃত হয়।",
  },
  {
    number: 27,
    symbol: "Co",
    nameBn: "কোবাল্ট",
    nameEn: "Cobalt",
    mass: 58.933,
    group: 9,
    period: 4,
    block: "d",
    category: "transition",
    electronConfig: "[Ar] 3d⁷ 4s²",
    electronegativity: 1.88,
    ionizationEnergy: 760,
    oxidationStates: "+2, +3",
    hscFact: "কোবাল্ট-৬০ (⁶⁰Co) আইসোটোপ ক্যান্সার চিকিৎসায় গামা রশ্মির উৎস হিসেবে ব্যবহৃত হয়।",
  },
  {
    number: 28,
    symbol: "Ni",
    nameBn: "নিকেল",
    nameEn: "Nickel",
    mass: 58.693,
    group: 10,
    period: 4,
    block: "d",
    category: "transition",
    electronConfig: "[Ar] 3d⁸ 4s²",
    electronegativity: 1.91,
    ionizationEnergy: 737,
    oxidationStates: "+2, +3",
    hscFact: "তেল বা চর্বির হাইড্রোজিনেশন বিক্রিয়ায় (মার্জারিন তৈরিতে) নিকেল প্রভাবক হিসেবে ব্যবহৃত হয়।",
  },
  {
    number: 29,
    symbol: "Cu",
    nameBn: "কপার (তামা)",
    nameEn: "Copper",
    mass: 63.546,
    group: 11,
    period: 4,
    block: "d",
    category: "transition",
    electronConfig: "[Ar] 3d¹⁰ 4s¹",
    electronegativity: 1.9,
    ionizationEnergy: 745,
    oxidationStates: "+1, +2",
    hscFact: "আউফবাউ নীতির ব্যতিক্রম (পূর্ণ 3d¹⁰ অরবিটালের অধিক স্থায়িত্বের জন্য 4s¹ হয়)। [Cu(NH₃)₄]²⁺ গাঢ় নীল জটিল যৌগ গঠন করে।",
  },
  {
    number: 30,
    symbol: "Zn",
    nameBn: "জিংক (দস্তা)",
    nameEn: "Zinc",
    mass: 65.38,
    group: 12,
    period: 4,
    block: "d",
    category: "transition",
    electronConfig: "[Ar] 3d¹⁰ 4s²",
    electronegativity: 1.65,
    ionizationEnergy: 906,
    oxidationStates: "+2",
    hscFact: "d-ব্লক হলেও অবস্থান্তর মৌল নয় (Zn²⁺ এ 3d¹⁰ পূর্ণ থাকে)। এর যৌগসমূহ বর্ণহীন এবং ডায়াম্যাগনেটিক।",
  },
];
